/* Backbone — game data. All content is static: no backend, no AI, no network. */

/* Trait keys: O openness, C conscientiousness, E extraversion,
   A agreeableness (healthy warmth), S emotional stability (inverse neuroticism). */
const TRAITS = {
  O: { name: "Openness", emoji: "🔭", desc: "Curiosity, trying new things" },
  C: { name: "Conscientiousness", emoji: "🧭", desc: "Follow-through, order, reliability" },
  E: { name: "Extraversion", emoji: "⚡", desc: "Social energy, initiative" },
  A: { name: "Warmth (Agreeableness)", emoji: "🤝", desc: "Kind and fair — never a doormat" },
  S: { name: "Emotional Stability", emoji: "🪨", desc: "Calm under fire, low anxiety" },
};

/* weights: how strongly the culture rewards each trait (1–5).
   directness: 0 = very high-context/indirect, 1 = very low-context/blunt.
   Broad-brush averages from cross-cultural research — not rules about individuals. */
const CULTURES = [
  /* ----- culture styles (pick these if your country isn't listed or you live between cultures) ----- */
  { id: "style-direct", group: "style", flag: "🎯", name: "Direct Individualist",
    blurb: "Low-context: say what you mean, mean what you say.",
    directness: 0.9, weights: { O: 4, C: 4, E: 4, A: 3, S: 4 },
    notes: ["Clear, brief requests read as competence, not rudeness.", "Hinting is invisible here — nobody decodes it."] },
  { id: "style-harmony", group: "style", flag: "🕊️", name: "Harmony Collectivist",
    blurb: "High-context: preserve face, read the room, keep the group smooth.",
    directness: 0.2, weights: { O: 3, C: 4, E: 3, A: 5, S: 4 },
    notes: ["Firmness lands best wrapped in face-saving language.", "A private word beats a public callout every time."] },
  { id: "style-honor", group: "style", flag: "🛡️", name: "Honor Culture",
    blurb: "Reputation, respect, and hospitality carry serious weight.",
    directness: 0.5, weights: { O: 3, C: 4, E: 4, A: 4, S: 4 },
    notes: ["Show respect first; then your boundary carries weight.", "Never make someone lose face in front of family or guests."] },
  { id: "style-nordic", group: "style", flag: "🌲", name: "Nordic Egalitarian",
    blurb: "Modest, consensus-minded, quietly direct. Don't be a show-off — or a pushover.",
    directness: 0.65, weights: { O: 4, C: 4, E: 3, A: 5, S: 4 },
    notes: ["Understate your wins; state your needs plainly.", "Consensus is prized, but silence isn't agreement — say your piece."] },
  { id: "style-latin", group: "style", flag: "💃", name: "Latin Expressive",
    blurb: "Warm, expressive, relationship-first. Simpatía matters.",
    directness: 0.4, weights: { O: 4, C: 3, E: 5, A: 4, S: 3 },
    notes: ["Warm the relationship before delivering the hard part.", "A hard flat 'no' can chill things — pair the no with warmth, not with surrender."] },
  { id: "style-hustle", group: "style", flag: "🚀", name: "Startup / Tech Hustle",
    blurb: "Bias to action, radical candor, ship it.",
    directness: 0.85, weights: { O: 5, C: 4, E: 4, A: 3, S: 4 },
    notes: ["Disagree openly, commit fast, keep receipts.", "Asking clearly for what you want is table stakes."] },

  /* ----- countries ----- */
  { id: "us", group: "country", flag: "🇺🇸", name: "United States",
    blurb: "Rewards initiative, optimism, and speaking up for yourself.",
    directness: 0.75, weights: { O: 4, C: 4, E: 5, A: 3, S: 4 },
    notes: ["Self-advocacy is expected — nobody negotiates your raise for you.", "Confidence reads as competence; hedging reads as doubt."] },
  { id: "ca", group: "country", flag: "🇨🇦", name: "Canada",
    blurb: "Polite directness: kind wrapping, clear contents.",
    directness: 0.55, weights: { O: 4, C: 4, E: 4, A: 5, S: 4 },
    notes: ["'Sorry' is punctuation, not surrender — keep the request firm.", "Courtesy is prized, but so is saying what you actually need."] },
  { id: "uk", group: "country", flag: "🇬🇧", name: "United Kingdom",
    blurb: "Understatement and dry wit; 'quite good' means excellent.",
    directness: 0.45, weights: { O: 4, C: 4, E: 3, A: 4, S: 4 },
    notes: ["Firmness works best delivered with calm understatement.", "'With respect…' can carry a very hard boundary politely."] },
  { id: "de", group: "country", flag: "🇩🇪", name: "Germany",
    blurb: "Sachlichkeit: directness about facts is respect, not rudeness.",
    directness: 0.9, weights: { O: 3, C: 5, E: 3, A: 3, S: 4 },
    notes: ["Say the problem plainly — sugarcoating wastes everyone's time.", "Reliability is the currency: do what you said, when you said."] },
  { id: "nl", group: "country", flag: "🇳🇱", name: "Netherlands",
    blurb: "World-champion bluntness. Hints will be cheerfully ignored.",
    directness: 0.95, weights: { O: 4, C: 4, E: 4, A: 3, S: 4 },
    notes: ["Direct feedback is normal — receiving it calmly earns respect.", "State your opinion; consensus comes from open disagreement."] },
  { id: "se", group: "country", flag: "🇸🇪", name: "Sweden",
    blurb: "Lagom and consensus: not too much, not too little, everyone heard.",
    directness: 0.6, weights: { O: 4, C: 4, E: 3, A: 5, S: 4 },
    notes: ["Boasting backfires; calm, brief clarity wins.", "Quiet doesn't mean passive — state your position once, clearly."] },
  { id: "fr", group: "country", flag: "🇫🇷", name: "France",
    blurb: "Debate is a sport and an act of respect. Defend your position.",
    directness: 0.7, weights: { O: 5, C: 3, E: 4, A: 3, S: 3 },
    notes: ["Pushback isn't hostility — it's engagement. Push back well.", "A well-argued 'non' is admired more than a mushy 'peut-être'."] },
  { id: "es", group: "country", flag: "🇪🇸", name: "Spain",
    blurb: "Expressive, social, relationship-first.",
    directness: 0.6, weights: { O: 4, C: 3, E: 5, A: 4, S: 3 },
    notes: ["Warmth and firmness mix fine — raise it over coffee, not email.", "Speaking with feeling is normal; going cold reads worse than heat."] },
  { id: "it", group: "country", flag: "🇮🇹", name: "Italy",
    blurb: "Fare bella figura: presentation, passion, and personal ties.",
    directness: 0.65, weights: { O: 4, C: 3, E: 5, A: 4, S: 3 },
    notes: ["Deliver hard messages with style and respect for dignity.", "Passionate disagreement is fine; humiliating someone is not."] },
  { id: "pl", group: "country", flag: "🇵🇱", name: "Poland",
    blurb: "Straight talk, low tolerance for corporate fluff.",
    directness: 0.7, weights: { O: 3, C: 4, E: 3, A: 3, S: 4 },
    notes: ["Skip the pep-talk wrapper — state the issue and the ask.", "Complaining together is bonding; solving it is respect."] },
  { id: "ru", group: "country", flag: "🇷🇺", name: "Russia",
    blurb: "Direct with substance, reserved with strangers, warm with friends.",
    directness: 0.8, weights: { O: 3, C: 4, E: 3, A: 3, S: 4 },
    notes: ["Smiling through a serious matter reads as unserious.", "Say it straight; softeners are for close friends, not negotiations."] },
  { id: "tr", group: "country", flag: "🇹🇷", name: "Türkiye",
    blurb: "Hospitality and honor: respect the person, then make your point.",
    directness: 0.5, weights: { O: 3, C: 4, E: 4, A: 4, S: 3 },
    notes: ["Honor the relationship first; then your firmness is heard.", "Refuse the request, never the person — keep the door warm."] },
  { id: "eg", group: "country", flag: "🇪🇬", name: "Egypt",
    blurb: "Relationship-first, expressive, face-conscious.",
    directness: 0.4, weights: { O: 3, C: 4, E: 4, A: 4, S: 3 },
    notes: ["Ease in with courtesy; abruptness closes ears.", "A no delivered with warmth and a reason keeps the bond intact."] },
  { id: "sa", group: "country", flag: "🇸🇦", name: "Saudi Arabia",
    blurb: "Dignity, hospitality, and patience shape every exchange.",
    directness: 0.35, weights: { O: 3, C: 4, E: 4, A: 4, S: 4 },
    notes: ["Never rush the courtesies — they are the negotiation.", "Firmness with dignity is respected; public confrontation is not."] },
  { id: "ng", group: "country", flag: "🇳🇬", name: "Nigeria",
    blurb: "Confidence, expressiveness, and hustle are admired.",
    directness: 0.6, weights: { O: 4, C: 4, E: 5, A: 4, S: 4 },
    notes: ["Carry yourself boldly — timidity gets talked over.", "Respect elders and titles, but still make your case."] },
  { id: "ke", group: "country", flag: "🇰🇪", name: "Kenya",
    blurb: "Community-minded, courteous, quietly resilient.",
    directness: 0.45, weights: { O: 3, C: 4, E: 4, A: 4, S: 4 },
    notes: ["Greet first, always — the relationship precedes the request.", "Harambee spirit: firm asks land better framed as shared goals."] },
  { id: "za", group: "country", flag: "🇿🇦", name: "South Africa",
    blurb: "Straight-talking warmth across many cultures; ubuntu matters.",
    directness: 0.6, weights: { O: 4, C: 4, E: 4, A: 4, S: 4 },
    notes: ["Be direct but human — 'a person is a person through other people'.", "Humor defuses; use it to hold a line without a fight."] },
  { id: "in", group: "country", flag: "🇮🇳", name: "India",
    blurb: "Hierarchy-aware and relationship-rich; 'no' often arrives indirectly.",
    directness: 0.4, weights: { O: 4, C: 4, E: 4, A: 4, S: 3 },
    notes: ["Refusals are wrapped ('we'll see', 'maybe') — wrap yours too, but keep the spine.", "Respect for seniority matters; disagree privately, propose alternatives."] },
  { id: "cn", group: "country", flag: "🇨🇳", name: "China",
    blurb: "Face (面子) and relationships (关系) are the operating system.",
    directness: 0.3, weights: { O: 3, C: 5, E: 3, A: 4, S: 4 },
    notes: ["Protect the other person's face and your no becomes acceptable.", "Indirect words, concrete follow-through — that combination is strength."] },
  { id: "jp", group: "country", flag: "🇯🇵", name: "Japan",
    blurb: "Wa (harmony), reading the air, and impeccable reliability.",
    directness: 0.15, weights: { O: 3, C: 5, E: 2, A: 5, S: 4 },
    notes: ["'That would be difficult…' is a complete and firm no.", "Boundaries live in what you reliably do, not in confrontation."] },
  { id: "kr", group: "country", flag: "🇰🇷", name: "South Korea",
    blurb: "Nunchi — the art of sensing the room — plus serious work ethic.",
    directness: 0.3, weights: { O: 3, C: 5, E: 3, A: 4, S: 4 },
    notes: ["Sense the mood, then speak — timing is half the message.", "Deference to seniors coexists with quietly holding your ground."] },
  { id: "th", group: "country", flag: "🇹🇭", name: "Thailand",
    blurb: "Jai yen (cool heart) and kreng jai (consideration) rule social life.",
    directness: 0.2, weights: { O: 3, C: 3, E: 4, A: 5, S: 4 },
    notes: ["Losing your temper loses the argument, instantly.", "A smile and a soft phrasing can carry a completely firm no."] },
  { id: "ph", group: "country", flag: "🇵🇭", name: "Philippines",
    blurb: "Pakikisama (getting along) and warmth, with real sensitivity to shame.",
    directness: 0.3, weights: { O: 3, C: 3, E: 5, A: 5, S: 4 },
    notes: ["Never shame anyone publicly — take it aside, keep it warm.", "Go-betweens and gentle humor are legitimate boundary tools."] },
  { id: "id", group: "country", flag: "🇮🇩", name: "Indonesia",
    blurb: "Rukun — social harmony — is the prime directive.",
    directness: 0.25, weights: { O: 3, C: 3, E: 4, A: 5, S: 4 },
    notes: ["Calm, patient, face-saving firmness wins the long game.", "'Belum' (not yet) politely does the work of 'no'."] },
  { id: "vn", group: "country", flag: "🇻🇳", name: "Vietnam",
    blurb: "Respect for hierarchy and composure, with fierce practicality.",
    directness: 0.3, weights: { O: 3, C: 4, E: 3, A: 4, S: 4 },
    notes: ["Keep composure — visible anger costs you the room.", "Persistence, politely repeated, is how firmness looks here."] },
  { id: "au", group: "country", flag: "🇦🇺", name: "Australia",
    blurb: "Direct, informal, allergic to self-importance (tall poppy!).",
    directness: 0.8, weights: { O: 4, C: 3, E: 4, A: 4, S: 4 },
    notes: ["Say it straight, take the mickey, don't big-note yourself.", "Whinging is fine over a beer; at work, state the fix you want."] },
  { id: "br", group: "country", flag: "🇧🇷", name: "Brazil",
    blurb: "Warmth and flexibility; a flat 'no' is rare — but yours can still be firm.",
    directness: 0.45, weights: { O: 4, C: 3, E: 5, A: 4, S: 3 },
    notes: ["Keep it warm and personal; cold formality creates distance.", "'Vou ver' (I'll see) often means no — learn to hear it and to say it."] },
  { id: "mx", group: "country", flag: "🇲🇽", name: "Mexico",
    blurb: "Simpatía and respect; harmony is protected in public.",
    directness: 0.35, weights: { O: 4, C: 3, E: 5, A: 5, S: 3 },
    notes: ["Deliver hard messages privately, wrapped in genuine courtesy.", "Warm greeting first, business second — always."] },
  { id: "ar", group: "country", flag: "🇦🇷", name: "Argentina",
    blurb: "Passionate debate over dinner is a love language.",
    directness: 0.7, weights: { O: 4, C: 3, E: 5, A: 3, S: 3 },
    notes: ["Argue with flair — backing down instantly reads as not caring.", "Strong opinions, warmly held, and still friends after."] },
];

/* ---------------- scenario deck ----------------
   kind: assertDirect | assertDiplo | good | ok | doormat | aggressive | avoid
   traits: XP deltas applied (scaled by culture weights). backbone: +1/-1 for the meter.
*/
const SCENARIOS = [
  {
    id: "coffee", tag: "Everyday", focus: "A",
    text: "The barista hands you a drink that is definitely not what you ordered — and you paid extra for yours.",
    choices: [
      { kind: "doormat", backbone: -1, traits: { A: 1, S: -2 },
        text: "Say nothing and drink it. It's fine. It's fine. (It's not fine.)",
        fb: "Classic doormat trade: you paid for your preference and then paid again with resentment. Small surrenders are the training data for big ones." },
      { kind: "aggressive", backbone: 0, traits: { A: -2, S: -1 },
        text: "\"Seriously? How hard is it to read a cup?\"",
        fb: "You got the drink and lost the room. Aggression isn't the opposite of doormat — it's the same anxiety wearing armor." },
      { kind: "assertDirect", backbone: 1, traits: { A: 1, S: 1, E: 1 },
        text: "\"Excuse me — I ordered the oat-milk mocha. Could you swap this one?\"",
        fb: "Clean, friendly, zero apology for having a preference. This is the whole game in one sentence." },
      { kind: "assertDiplo", backbone: 1, traits: { A: 2, S: 1 },
        text: "Smile: \"I think this might be someone else's — mine was the oat-milk mocha. No rush!\"",
        fb: "Face-saving for the barista, outcome unchanged for you. Diplomatic assertiveness still gets the right drink." },
    ],
  },
  {
    id: "flaky-friend", tag: "Friends", focus: "A",
    text: "Your friend cancels on you last-minute for the fourth time this month. Today they text: \"sooo sorry!! rain check?? 🥺\"",
    choices: [
      { kind: "doormat", backbone: -1, traits: { S: -2 },
        text: "\"Omg no worries at all!! Whenever works for you!! 😊\"",
        fb: "Four cancellations, zero cost. You just taught them your time is a suggestion. Resentment is now doing the talking you refused to do." },
      { kind: "aggressive", backbone: 0, traits: { A: -2, S: -1 },
        text: "\"Wow. Fourth time. Don't bother rescheduling.\"",
        fb: "The frustration is legitimate; the nuke loses the friend without ever telling them what would fix it." },
      { kind: "assertDirect", backbone: 1, traits: { A: 1, S: 1 },
        text: "\"Honestly? The last-minute cancels are wearing on me. I'd love to see you — can we pick a time you're sure about?\"",
        fb: "Names the pattern, states the feeling, offers the path forward. Textbook assertive: honest AND warm." },
      { kind: "assertDiplo", backbone: 1, traits: { A: 2, S: 1 },
        text: "\"Rain check's fine — but let's make the next one solid. You pick a day you're 100% on and I'll build around it.\"",
        fb: "Gentle on the surface, firm underneath: the pattern is named ('make the next one solid') and they now own the commitment." },
    ],
  },
  {
    id: "friday-boss", tag: "Work", focus: "A",
    text: "5:45pm Friday. Your boss drops a \"quick task\" on you — third Friday in a row. You have plans at 7.",
    choices: [
      { kind: "doormat", backbone: -1, traits: { S: -2, C: 1 },
        text: "Cancel your plans. Again. Reply \"on it!\" with an enthusiasm you do not feel.",
        fb: "Reliable? Yes. But you're training your boss that your Friday evenings are free inventory. Doormat compliance now guarantees Friday #4." },
      { kind: "aggressive", backbone: 0, traits: { A: -2, S: -2 },
        text: "\"This is honestly ridiculous. Every Friday. Do you plan at all?\"",
        fb: "True feelings, career-limiting delivery. Attacking their competence turns a boundary conversation into a status fight you can't win." },
      { kind: "assertDirect", backbone: 1, traits: { S: 2, C: 1 },
        text: "\"I can't tonight — I have plans. I'll have it done by 10am Monday, or tell me what to drop if it truly can't wait.\"",
        fb: "No excuses, no apology spiral — a clear no plus two workable options. Bosses respect people who manage their own perimeter." },
      { kind: "assertDiplo", backbone: 1, traits: { A: 1, S: 1, C: 1 },
        text: "\"Happy to make sure this gets done well — tonight isn't possible, so should I prioritize it first thing Monday, or swap it with the Henderson report?\"",
        fb: "Frames the boundary as prioritization — which is literally your boss's language. The no is invisible and unmissable at the same time." },
    ],
  },
  {
    id: "fridge-thief", tag: "Home", focus: "A",
    text: "Your roommate has eaten your labeled leftovers three times this week. You just opened the fridge to find your lunch gone. Again.",
    choices: [
      { kind: "doormat", backbone: -1, traits: { S: -2 },
        text: "Buy a mini-fridge for your room. Problem solved via retreat.",
        fb: "You just paid money to avoid one sentence. The lesson your roommate learned: consequences of eating your food = you buy appliances." },
      { kind: "aggressive", backbone: 0, traits: { A: -2, S: -1 },
        text: "Leave a passive-aggressive note on the fridge: \"To WHOEVER keeps STEALING…\"",
        fb: "Notes escalate; conversations resolve. Public shaming makes them defensive and makes you the dramatic one." },
      { kind: "assertDirect", backbone: 1, traits: { A: 1, S: 1 },
        text: "\"Hey — my lunch keeps disappearing. Labeled stuff is off-limits. If you're hungry, ask, I'll usually share.\"",
        fb: "Direct, generous, and completely clear. The offer to share proves the boundary isn't hostility — it's just a boundary." },
      { kind: "assertDiplo", backbone: 1, traits: { A: 2, S: 1 },
        text: "\"Should we do a food-splitting system? Because the current one where you eat my lunch isn't working for me. 😄\"",
        fb: "Humor carries the message without the sting — but the message ('this stops') arrives fully intact. High-skill move." },
    ],
  },
  {
    id: "credit-thief", tag: "Work", focus: "A",
    text: "In the team meeting, a coworker presents your idea — the one you told them at lunch — as their own. People are nodding.",
    choices: [
      { kind: "doormat", backbone: -1, traits: { S: -3 },
        text: "Say nothing. Vent to your partner tonight. Update your resume bitterly.",
        fb: "Silence here is expensive: the org chart now believes the wrong story. Doormat moments in public compound like interest." },
      { kind: "aggressive", backbone: 0, traits: { A: -2, S: -2 },
        text: "\"Wow, that's literally MY idea. I told you that at lunch. Unbelievable.\"",
        fb: "You're right, and now the meeting is about your outburst instead of your idea. Accuracy isn't enough — delivery decides who wins the room." },
      { kind: "assertDirect", backbone: 1, traits: { E: 2, S: 1 },
        text: "\"Glad this landed — it's the concept I shared with Sam at lunch. Let me walk through the part I haven't shared yet.\"",
        fb: "Reclaims authorship in one breath and immediately adds value. No accusation needed: ownership is demonstrated, not litigated." },
      { kind: "assertDiplo", backbone: 1, traits: { A: 1, E: 1, S: 1 },
        text: "\"Sam and I were discussing this at lunch — happy to see it resonate. I can send the full write-up I drafted last week.\"",
        fb: "The word 'my write-up, last week' does the correcting; Sam keeps face, the room recalibrates, and you look composed doing it." },
    ],
  },
  {
    id: "loan-again", tag: "Friends", focus: "A",
    text: "A friend who still owes you $200 from March asks to borrow another $150. \"You know I'm good for it!\"",
    choices: [
      { kind: "doormat", backbone: -1, traits: { S: -2 },
        text: "Lend it. Avoiding two seconds of awkwardness costs $150. A bargain?",
        fb: "You're not buying their friendship — you're renting their approval, and the rate keeps going up. Kind people can say no about money." },
      { kind: "aggressive", backbone: 0, traits: { A: -2 },
        text: "\"Good for it? You still owe me $200! Everyone knows you never pay anyone back.\"",
        fb: "The public shaming turns your legitimate grievance into their story about your cruelty. The debt is real; the humiliation is optional." },
      { kind: "assertDirect", backbone: 1, traits: { S: 2 },
        text: "\"Not while the $200 from March is still open. Square that first, then ask me again.\"",
        fb: "The broken-record classic: one clear condition, no character trial, no apology. This is what respecting your own money sounds like." },
      { kind: "assertDiplo", backbone: 1, traits: { A: 1, S: 1 },
        text: "\"I've got a rule now — one loan at a time. Once March is settled I'm happy to help again.\"",
        fb: "'The rule' is a beautiful face-saver: it says no for you, impersonally, forever. They can be annoyed at the rule instead of you." },
    ],
  },
  {
    id: "dinner-critic", tag: "Family", focus: "A",
    text: "At the family dinner, your uncle starts in again: \"Still doing that little job of yours? Your cousin just bought a house, you know.\"",
    choices: [
      { kind: "doormat", backbone: -1, traits: { S: -2 },
        text: "Laugh weakly, mumble \"yeah, haha,\" and study your plate intensely for the next hour.",
        fb: "Every weak laugh renews his license. He's not going to stop on his own — this show gets cancelled by you or it runs forever." },
      { kind: "aggressive", backbone: 0, traits: { A: -2, S: -1 },
        text: "\"At least I didn't need Grandpa's money to do it. How IS that going?\"",
        fb: "Direct hit, mutual destruction. Now it's a feud, the table picks sides, and Thanksgiving is ruined until 2031." },
      { kind: "assertDirect", backbone: 1, traits: { S: 2 },
        text: "Calm, level, eye contact: \"I'm happy with my path. I'm not discussing my career at dinner anymore.\" Then turn and ask your aunt about her garden.",
        fb: "A boundary plus an immediate topic change is the power combo — you didn't defend your life, you declined the trial entirely." },
      { kind: "assertDiplo", backbone: 1, traits: { A: 1, S: 2 },
        text: "Smile: \"Congrats to him — houses are great. My thing's going well too. Anyway — who made this incredible dessert?\"",
        fb: "Fogging: agree with the harmless part, glide past the hook, redirect. He threw a barb and it landed in butter. Deeply annoying to bullies." },
    ],
  },
  {
    id: "pushy-sales", tag: "Everyday", focus: "A",
    text: "A gym rep has been pitching you for 15 minutes and is now filling out the contract 'just to show you.' \"So — shall we start you Monday?\"",
    choices: [
      { kind: "doormat", backbone: -1, traits: { S: -2, C: -1 },
        text: "Sign up. You can always cancel later (you will never cancel; there is a cancellation fee).",
        fb: "You just paid a subscription to avoid disappointing a stranger who was professionally pressuring you. That's the doormat endgame." },
      { kind: "avoid", backbone: -1, traits: { S: -1 },
        text: "\"I… need to check with my partner. And my schedule. I'll definitely come back Thursday!\" (You will not.)",
        fb: "Fake maybes feel polite but cost you twice — you endure the pitch AND the follow-up calls. A clean no would've freed you 14 minutes ago." },
      { kind: "assertDirect", backbone: 1, traits: { S: 2 },
        text: "\"No thanks — I'm not signing anything today.\" (He counters.) \"I understand. Still no.\" (He counters again.) \"Still no. Have a good one.\"",
        fb: "The broken record: same calm no, zero new reasons — because every reason you give is a handle for the counter-pitch. Reasons are for people you owe them to." },
      { kind: "assertDiplo", backbone: 1, traits: { A: 1, S: 1 },
        text: "\"You've been great, and it's a no today. If I change my mind you'll be my first call.\"",
        fb: "Warm packaging, immovable contents. Notice there's no fake maybe in it — 'if I change my mind' puts the ball permanently in your court." },
    ],
  },
  {
    id: "night-noise", tag: "Home", focus: "A",
    text: "1:30am, third night this week: your neighbor's bass is shaking your wall. You have a 7am start.",
    choices: [
      { kind: "doormat", backbone: -1, traits: { S: -2 },
        text: "Buy better earplugs. Fantasize about moving. Sleep 4 hours.",
        fb: "You're absorbing 100% of the cost of their party. They'd likely turn it down if asked — most people aren't villains, just oblivious." },
      { kind: "aggressive", backbone: 0, traits: { A: -2, S: -1 },
        text: "Pound on their door at 1:30am and let three nights of rage do the introductions.",
        fb: "Right cause, wrong ambassador. Rage at their door at 1am starts a neighbor war that outlasts the playlist." },
      { kind: "assertDirect", backbone: 1, traits: { S: 1, E: 1 },
        text: "Next day, knock: \"Hey, I'm next door. The bass carries after midnight and I start at 7. Can you keep it low on weeknights?\"",
        fb: "Daylight diplomacy: specific problem, specific ask, no accusation of character. This resolves 90% of neighbor conflicts on the first try." },
      { kind: "assertDiplo", backbone: 1, traits: { A: 1, S: 1 },
        text: "Catch them in the hall: \"Your speakers are honestly impressive — and my wall agrees. Weeknights after 12, could you give it a rest? I'd owe you.\"",
        fb: "The compliment buys goodwill, the ask stays fully intact. Charm is a delivery system, not a substitute, for the boundary." },
    ],
  },
  {
    id: "slacker-teammate", tag: "Work", focus: "A",
    text: "Group presentation tomorrow. Your teammate has produced nothing except \"lol we got this.\" It's 4pm.",
    choices: [
      { kind: "doormat", backbone: -1, traits: { S: -2, C: 1 },
        text: "Do their half tonight. Say nothing. Let them take half the credit tomorrow.",
        fb: "The all-nighter rescues the deadline and finances their next free ride. Doormats are how slackers fund their lifestyle." },
      { kind: "aggressive", backbone: 0, traits: { A: -2, S: -1 },
        text: "\"You're useless. I'm telling the boss exactly who did what.\"",
        fb: "Even if true, you've made an enemy and pre-poisoned tomorrow's presentation. Escalation is a tool — the LAST tool, not the first." },
      { kind: "assertDirect", backbone: 1, traits: { C: 2, S: 1 },
        text: "\"Slides 6–10 are yours, done by 9pm, or I present my half solo and say so plainly if I'm asked who did what. Your call.\"",
        fb: "A deadline, a consequence you fully control, and no rage required. Consequences you can actually enforce are worth ten threats you can't." },
      { kind: "assertDiplo", backbone: 1, traits: { A: 1, C: 1, S: 1 },
        text: "\"We're presenting to the boss in 18 hours and half the deck is empty — walk me through your plan for 6–10 so I know we're safe.\"",
        fb: "'Walk me through your plan' hands the problem back politely but unmistakably. If the plan is vapor, that's now visible to both of you at 4pm, not 9am." },
    ],
  },
  {
    id: "date-drink", tag: "Social", focus: "A",
    text: "You've decided not to drink tonight. At the bar, the group's ringleader announces shots. \"Don't be boring! One won't kill you!\"",
    choices: [
      { kind: "doormat", backbone: -1, traits: { S: -2 },
        text: "Take the shot. And the next. Your 'no' lasted nine seconds.",
        fb: "The issue isn't the drink — it's learning that your decisions dissolve under two sentences of pressure. Tonight it's shots; the pattern is the problem." },
      { kind: "aggressive", backbone: 0, traits: { A: -2 },
        text: "\"Maybe I don't want to end up like you, Dave.\"",
        fb: "You defended the boundary and torched the evening. A no doesn't need a counter-attack to be valid." },
      { kind: "assertDirect", backbone: 1, traits: { S: 2 },
        text: "\"Nope, not tonight.\" (Pushback.) \"Still no — but I'll get the next round.\" Then just… keep having fun.",
        fb: "No excuse, no health lecture, no wavering — plus staying warm and staying present. People drop it fast when the no is boring and cheerful." },
      { kind: "assertDiplo", backbone: 1, traits: { A: 1, S: 1, E: 1 },
        text: "Raise your soda: \"I'm on this tonight — someone's gotta remember what happens. Cheers!\"",
        fb: "Deflection with a wink: no confrontation, no compliance. You made your no fun to accept, which is diplomatic assertiveness at its best." },
    ],
  },
  {
    id: "raise-ask", tag: "Work", focus: "E",
    text: "You've led two successful launches this year. Salary review is next week. Your manager hasn't mentioned a raise.",
    choices: [
      { kind: "avoid", backbone: -1, traits: { S: -1, E: -1 },
        text: "Say nothing. If they valued you, they'd offer. Surely the work speaks for itself.",
        fb: "Work is mute; people who narrate their work get paid for it. Waiting to be noticed is the doormat strategy in a business-casual costume." },
      { kind: "ok", backbone: 0, traits: { C: 1 },
        text: "Drop hints about cost of living and how expensive rent's gotten, hoping they connect the dots.",
        fb: "Hints put the work on them and the plausible deniability on you. Better than silence — but a direct ask with evidence beats vibes every time." },
      { kind: "assertDirect", backbone: 1, traits: { E: 2, C: 1, S: 1 },
        text: "Book a meeting: \"I want to discuss my compensation. Both launches beat targets — here are the numbers. I'm asking for X.\"",
        fb: "Specific evidence, specific number, zero apology. The worst realistic outcome is 'not yet' plus a roadmap — which is still progress." },
      { kind: "assertDiplo", backbone: 1, traits: { E: 1, C: 1, S: 1 },
        text: "Before the review: \"When we meet next week, I'd like compensation on the agenda — I'll bring a summary of this year's results.\"",
        fb: "Setting the agenda in advance is a soft power move: no ambush, full preparation, and they walk in already knowing you know your worth." },
    ],
  },

  /* ---- emotional stability / anti-anxiety rounds ---- */
  {
    id: "presentation-night", tag: "Anxiety", focus: "S",
    text: "11pm. Big presentation at 9am. Your heart is doing a drum solo and your brain offers a highlight reel of every possible disaster.",
    choices: [
      { kind: "avoid", backbone: 0, traits: { S: -2 },
        text: "Rehearse the disaster reel in bed for three hours. Vigilance = preparation, right?",
        fb: "Rumination feels like preparing but it's just rehearsing fear. Your 9am self inherits the anxiety AND the sleep debt." },
      { kind: "avoid", backbone: 0, traits: { S: -3, C: -1 },
        text: "Draft the 'I think I'm coming down with something' text to your manager.",
        fb: "Avoidance is anxiety's favorite meal: instant relief now, bigger fear next time. Every dodge teaches your brain the thing really was dangerous." },
      { kind: "good", backbone: 0, traits: { S: 2, C: 1 },
        text: "20 minutes: run the opening twice out loud, note your first line on a card. Then shower, screens off, bed.",
        fb: "Bounded preparation then a hard stop — you did the one thing that helps and refused the ten that don't. That's what control actually feels like." },
      { kind: "good", backbone: 0, traits: { S: 3 },
        text: "Name it: \"That racing heart is adrenaline — the same chemical as excitement. My body is fueling up, not breaking down.\" Slow exhales, 4 minutes.",
        fb: "Reappraisal is evidence-backed: 'I'm excited' outperforms 'calm down' because it works WITH the arousal. Long exhales then hand the body the brakes." },
    ],
  },
  {
    id: "party-stranger", tag: "Anxiety", focus: "S",
    text: "You're at a party where you know exactly one person, and they just got absorbed into another conversation. The exit is right there.",
    choices: [
      { kind: "avoid", backbone: 0, traits: { S: -2, E: -1 },
        text: "Slip out. Text 'had to run!' from the bus. Feel relief, then a faint disappointment that lasts longer than the party would have.",
        fb: "The relief of escape is real — and it's the exact mechanism that makes the next party scarier. Avoidance pays interest, always." },
      { kind: "ok", backbone: 0, traits: { S: -1 },
        text: "Guard the snack table and study your phone with the intensity of a bomb-disposal technician.",
        fb: "Physically present, socially bunkered. Half-credit: you didn't flee, but safety behaviors keep the fear on life support." },
      { kind: "good", backbone: 0, traits: { S: 2, E: 2 },
        text: "Set a tiny contract: 20 minutes, two real conversations, then you may leave guilt-free. Start with \"How do you know the host?\"",
        fb: "Exposure with an exit ramp — the gold standard. Small defined goals beat 'be social' every time, and you usually stay past the 20 minutes." },
      { kind: "good", backbone: 0, traits: { S: 2, E: 1 },
        text: "Remember the spotlight effect: nobody is grading you — they're all worrying about themselves. Go refill someone's drink and ask a question.",
        fb: "The spotlight effect is one of psychology's most replicated comforts: people notice you about 50% as much as you think. Act on that math." },
    ],
  },
  {
    id: "typo-email", tag: "Anxiety", focus: "S",
    text: "You just noticed the email you sent to the entire company says 'Please find attached my analisys.' It has been 11 minutes. No one has replied.",
    choices: [
      { kind: "avoid", backbone: 0, traits: { S: -3 },
        text: "Read it 14 more times. Imagine the group chats. Draft three apology emails. Consider new employment.",
        fb: "Catastrophizing: one typo has become a career event. Run the actual evidence — how many colleagues' typos can YOU remember? Exactly." },
      { kind: "doormat", backbone: -1, traits: { S: -2, A: 1 },
        text: "Send a lengthy apology email to everyone about your carelessness and your commitment to higher standards going forward.",
        fb: "The apology email is 50x more visible than the typo. Over-apologizing for microscopic crimes teaches people to see you as fragile." },
      { kind: "good", backbone: 0, traits: { S: 3 },
        text: "Snort at 'analisys,' forward the corrected file only to the people who actually need it, move on with your day.",
        fb: "Proportional response: fix what matters, skip the theater. Emotionally stable people aren't typo-free — they're just done with it in 90 seconds." },
      { kind: "good", backbone: 0, traits: { S: 2 },
        text: "Run the 10-10-10 check: does this matter in 10 minutes? 10 weeks? 10 months? Two noes and a laugh. Close the sent folder.",
        fb: "Zooming out is a portable skill — anxiety shrinks time horizons to the next 10 minutes; deliberately stretching them is the antidote." },
    ],
  },
  {
    id: "no-reply", tag: "Anxiety", focus: "S",
    text: "Your close friend read your message two days ago. No reply. They posted a meme yesterday.",
    choices: [
      { kind: "avoid", backbone: 0, traits: { S: -3 },
        text: "Scroll your entire chat history for the offense you must have committed. Compose theories. Sleep badly.",
        fb: "Mind reading: you've written their inner monologue and cast yourself as the villain. Two days of evidence-free trial — verdict guilty. That's the distortion, not the data." },
      { kind: "ok", backbone: 0, traits: { S: -1 },
        text: "Send \"hahah also this!!\" with another meme, watch delivery status like mission control.",
        fb: "The probe text is checking behavior — anxiety management outsourced to their read receipts. Mild, human, but it feeds the loop." },
      { kind: "good", backbone: 0, traits: { S: 3 },
        text: "Generate three boring explanations: busy week, opened it in bed, meant to reply and forgot. Notice all three are likelier than 'secretly hates me.'",
        fb: "The alternative-explanations drill is core CBT: anxiety always files the worst theory first. Making it compete with boring ones usually ends the case." },
      { kind: "good", backbone: 0, traits: { S: 2, E: 1 },
        text: "If it still matters in a day, just ask: \"Hey, all good? No stress — just checking in.\" Then put the phone down and live your life.",
        fb: "Direct, light, once. Checking reality beats simulating it — and 'once, then done' is what keeps asking from becoming monitoring." },
    ],
  },
  {
    id: "job-rejection", tag: "Setback", focus: "S",
    text: "\"We've decided to move forward with other candidates.\" The job you wanted. The one you told people about.",
    choices: [
      { kind: "avoid", backbone: 0, traits: { S: -2 },
        text: "\"I always blow it. I'm just not a person things work out for.\" Cancel this week's other applications.",
        fb: "Overgeneralization: one data point became a life sentence. Notice the move from 'this attempt failed' to 'I am a failure' — that's the thought to arrest." },
      { kind: "ok", backbone: 0, traits: { S: 0 },
        text: "Delete the email, tell no one, apply to five more jobs tonight in a grim fugue.",
        fb: "Resilience-ish — but unprocessed losses tend to leak. Ten minutes of 'that stings, and here's what I'll try differently' beats a fugue state." },
      { kind: "good", backbone: 0, traits: { S: 2, C: 1 },
        text: "Reply thanking them and asking one question: \"Any feedback on where I fell short? It would genuinely help.\"",
        fb: "Feedback-seeking after rejection is elite behavior — most people can't stomach it, which is exactly why the ones who do improve fastest." },
      { kind: "good", backbone: 0, traits: { S: 2 },
        text: "Give the sting a container: tonight you're allowed to be gutted. Tomorrow at 9am, the postmortem: what was in my control, what wasn't, what changes.",
        fb: "Feel-it-then-file-it. Emotions denied go underground and unionize; emotions given a timeslot process and pass. Stability isn't numbness — it's scheduling." },
    ],
  },
  {
    id: "results-weekend", tag: "Anxiety", focus: "S",
    text: "Your doctor's office: \"Results will be ready Monday.\" It is Friday, 5:01pm.",
    choices: [
      { kind: "avoid", backbone: 0, traits: { S: -3 },
        text: "Search your symptoms until 2am. By Saturday you have diagnosed yourself with three conditions, two of them incompatible.",
        fb: "Reassurance-seeking that manufactures its own dread — search engines rank by alarm, not by likelihood. Dr. Google runs a fear clinic." },
      { kind: "ok", backbone: 0, traits: { S: -1 },
        text: "Tell nobody and white-knuckle the weekend with forced cheerfulness and gritted teeth.",
        fb: "Suppression is the gym membership you pay for and never use — studies show pushed-down worry rebounds harder. Containment ≠ suppression; see the other options." },
      { kind: "good", backbone: 0, traits: { S: 3 },
        text: "Schedule the worry: 15 minutes Saturday morning, on paper, then closed. When it knocks later: \"Noted — you have an appointment tomorrow at 9.\"",
        fb: "Worry scheduling sounds absurd and is remarkably well-supported: worry that's contained loses its ambush power. You control the meeting times now." },
      { kind: "good", backbone: 0, traits: { S: 2, E: 1 },
        text: "Acknowledge it: \"Uncertainty until Monday — that's real and it's uncomfortable.\" Then book the weekend full: hike, friends, that film. Feed the mind actual events.",
        fb: "Acceptance plus behavioral activation — you're not pretending it's fine, you're refusing to hold a three-day vigil for information that arrives Monday regardless." },
    ],
  },

  /* ---- conscientiousness rounds ---- */
  {
    id: "two-week-project", tag: "Discipline", focus: "C",
    text: "New project assigned, due in two weeks. It's big, vague, and nobody will check on you until the end.",
    choices: [
      { kind: "avoid", backbone: 0, traits: { C: -2, S: -1 },
        text: "\"Two weeks is forever.\" File it under Later. Later is a real place where work does itself, presumably.",
        fb: "Future-you is not a different, more disciplined person — they're you, minus twelve days, plus panic. Procrastination is borrowing stress at 40% interest." },
      { kind: "ok", backbone: 0, traits: { C: 1 },
        text: "Spend today making a beautiful color-coded plan with milestones. Feel extremely productive. Start actual work… soon.",
        fb: "Planning is progress until it becomes procrastination in a nicer outfit. The plan needed 20 minutes; the other 3 hours were avoidance with stationery." },
      { kind: "good", backbone: 0, traits: { C: 3 },
        text: "Today, 25 ugly minutes: open the doc, dump every thought, identify the scariest sub-task. Tomorrow, do the scary one first.",
        fb: "Starting badly beats planning beautifully — the unstarted task generates dread all week (the Zeigarnik effect); the started one generates momentum." },
      { kind: "good", backbone: 0, traits: { C: 2, S: 1 },
        text: "Slice it into 6 chunks, calendar each one as a fake earlier deadline, tell a colleague your day-10 'done' date.",
        fb: "Implementation intentions + social stakes: the two most replicated commitment devices in the literature, stacked. Deadlines you announce are deadlines you keep." },
    ],
  },
  {
    id: "lost-keys", tag: "Discipline", focus: "C",
    text: "Twenty minutes of morning panic: keys in yesterday's jacket, wallet in the gym bag, phone… ringing somewhere. This is the third time this month.",
    choices: [
      { kind: "avoid", backbone: 0, traits: { C: -1 },
        text: "\"I'm just a chaotic person 🤷 it's part of my charm.\" Sprint for the bus. Same time tomorrow.",
        fb: "'That's just how I am' is how traits stay frozen. Conscientiousness isn't a personality gift — it's mostly systems that boring-proof your mornings." },
      { kind: "ok", backbone: 0, traits: { C: 1 },
        text: "Resolve, with great sincerity, to Be More Careful and Really Pay Attention from now on.",
        fb: "Willpower is a battery; systems are solar. 'Try harder' has a 100% historical failure rate on this exact problem — you have three data points this month." },
      { kind: "good", backbone: 0, traits: { C: 3 },
        text: "Tonight: a bowl by the door. Keys, wallet, badge live there — the rule is 'hand touches door, stuff goes in bowl.' One week trial.",
        fb: "One dumb bowl beats a thousand resolutions. Environment design is conscientiousness for humans who don't want to think before coffee — i.e., all humans." },
      { kind: "good", backbone: 0, traits: { C: 2, S: 1 },
        text: "Do a 10-minute 'friction audit': list this month's three scrambles, design one tiny fix for each (bowl, hook, phone charger location).",
        fb: "Treating your own life like a process to debug is peak conscientiousness — fix the system once instead of blaming the operator daily." },
    ],
  },
  {
    id: "gym-jan", tag: "Discipline", focus: "C",
    text: "You planned a 6am workout. It is 6:04am, dark, cold, and the bed has never loved you this much.",
    choices: [
      { kind: "avoid", backbone: 0, traits: { C: -2 },
        text: "Snooze. The streak is dead anyway; might as well restart fresh on Monday. Or the 1st. Something clean.",
        fb: "All-or-nothing thinking, gym edition: one missed rep becomes a cancelled identity. Perfectionism is procrastination's business partner." },
      { kind: "ok", backbone: 0, traits: { C: 0 },
        text: "Negotiate: tonight after work instead. (Evening-you has declined 9 of the last 10 of these handoffs, but maybe tonight.)",
        fb: "Rescheduling is fine once; as a pattern it's just snoozing with extra steps. Check evening-you's actual attendance record before trusting them again." },
      { kind: "good", backbone: 0, traits: { C: 3, S: 1 },
        text: "Invoke the 2-minute rule: you only have to put on shoes and step outside. That's it. (You know what happens once the shoes are on.)",
        fb: "Shrink the ask until refusal is absurd — the 2-minute rule works because starting is the whole battle. Nobody drives to the gym to do one squat." },
      { kind: "good", backbone: 0, traits: { C: 2 },
        text: "Do 15 minutes at home, right now — the pre-planned 'bad weather version' you keep for mornings exactly like this.",
        fb: "A shrunken backup plan keeps the identity alive: 'I'm someone who trains' survives on 15 minutes. Streaks die from zero days, never from small ones." },
    ],
  },

  /* ---- extraversion rounds ---- */
  {
    id: "network-event", tag: "Social", focus: "E",
    text: "Industry mixer. You know no one. Everyone else appears to have been friends since childhood (they have not).",
    choices: [
      { kind: "avoid", backbone: 0, traits: { E: -2, S: -1 },
        text: "Do one lap with your badge on, speak to zero humans, leave, report 'networking done.'",
        fb: "The lap-and-leave: attendance without contact. The event cost you an evening and paid you nothing — approach is the only currency here." },
      { kind: "ok", backbone: 0, traits: { E: 1 },
        text: "Fire business cards at anyone who makes eye contact. Volume strategy. 31 cards deployed.",
        fb: "Contact without connection. One real 10-minute conversation outperforms 31 cards — people remember questions you asked, never cards you dealt." },
      { kind: "good", backbone: 0, traits: { E: 3, S: 1 },
        text: "Find another person standing alone (there's always one). \"These things are brutal solo — mind if I join you? What brings you here?\"",
        fb: "Targeting fellow solo-standers is the highest-percentage social play that exists: they're relieved, you're brave, and 'what brings you here' does the rest." },
      { kind: "good", backbone: 0, traits: { E: 2, O: 1 },
        text: "Set a quota of three genuine conversations where you mostly ask and listen. Quality bar: learn one surprising thing per person.",
        fb: "Curiosity converts small talk into real talk. People rate great listeners as great conversationalists — the trick is the questions were the performance." },
    ],
  },
  {
    id: "toast-time", tag: "Social", focus: "E",
    text: "Your best friend's celebration dinner. Someone clinks a glass: \"Speech from you next!\" Twelve faces turn to you.",
    choices: [
      { kind: "avoid", backbone: 0, traits: { E: -2, S: -1 },
        text: "\"Oh no no no, I'm terrible at this—\" Wave it away until the moment dies. Feel relieved, then a little robbed.",
        fb: "The dodge felt like survival, but you'll replay the toast you didn't give more than any toast you could've flubbed. Regret weighs more than cringe." },
      { kind: "ok", backbone: 0, traits: { E: 1 },
        text: "\"To Maya!\" Raise glass. Sit down. Technically a toast. Four words.",
        fb: "You cleared the bar by lying under it. Fine — but these tiny stages are free reps for every bigger room you'll ever stand in." },
      { kind: "good", backbone: 0, traits: { E: 3, S: 1 },
        text: "Stand up, tell the 60-second story of the day Maya drove three hours for you, land on \"that's who we're toasting.\" Voice shaky at first. Nobody cares.",
        fb: "One story, one point, sit down — the entire formula for public speaking. The shake in your voice registered to exactly one person in the room: you." },
      { kind: "good", backbone: 0, traits: { E: 2, A: 1 },
        text: "\"I'll go — but first, everyone say one word for Maya, and I'll bring it home.\" Collect twelve words, weave three of them into your closer.",
        fb: "Turning a solo into a chorus — social initiative AND generosity. You lowered your own stakes and raised the room's warmth in one move." },
    ],
  },

  /* ---- openness rounds ---- */
  {
    id: "weird-menu", tag: "Novelty", focus: "O",
    text: "Your colleague from Chennai invites the team to her favorite spot: a menu with zero familiar words and, she promises, 'the best thing you've never eaten.'",
    choices: [
      { kind: "avoid", backbone: 0, traits: { O: -2 },
        text: "\"I'll just eat before we go and get a lemonade there.\" Safe. Also the single most closed-off sentence available to you.",
        fb: "Every unfamiliar menu declined keeps the world exactly the size it already is. Openness compounds — and so does its absence." },
      { kind: "ok", backbone: 0, traits: { O: 1 },
        text: "Scan for the one dish that resembles something you know. Order the closest thing to what you always get.",
        fb: "A toe in the water — genuinely better than dinner at home. But 'the familiar thing, elsewhere' is novelty with the novelty removed." },
      { kind: "good", backbone: 0, traits: { O: 3, A: 1 },
        text: "\"Order for me — whatever you'd pick for someone you like.\" Eat what arrives. Ask what everything is called.",
        fb: "Delegating the choice to an enthusiast is the openness cheat code: maximum discovery, zero decision anxiety, and it honors her expertise. Everyone wins." },
      { kind: "good", backbone: 0, traits: { O: 2, E: 1 },
        text: "Order the dish whose name you can't pronounce, on purpose. Announce this policy. Let the table coach you through it.",
        fb: "'The unpronounceable one, please' is a repeatable life policy, not just an order — a tiny standing bet that the unknown is usually worth it." },
    ],
  },
  {
    id: "odd-approach", tag: "Novelty", focus: "O",
    text: "In review, the new hire proposes rebuilding your process completely differently — \"it's how we did it at my old company.\" Your process. The one you designed.",
    choices: [
      { kind: "avoid", backbone: 0, traits: { O: -2, A: -1 },
        text: "\"We've tried things like that. It doesn't fit how we work here.\" (You have not tried it. It might fit.)",
        fb: "'We've always done it this way' is how strong processes calcify into monuments. The prick you felt was ego, not judgment — learn to tell them apart." },
      { kind: "ok", backbone: 0, traits: { O: 1 },
        text: "\"Interesting — drop the details in a doc sometime.\" (The doc will pull 0 views, and both of you suspect this.)",
        fb: "The polite landfill. Half-open: you didn't kill the idea, you just routed it somewhere ideas go to be unread." },
      { kind: "good", backbone: 0, traits: { O: 3, S: 1 },
        text: "\"Walk me through it — specifically what it fixes that ours doesn't. If it survives twenty minutes of hard questions, we pilot it on one project.\"",
        fb: "Openness with a filter: genuinely persuadable AND rigorously skeptical. 'Pilot on one project' is how you buy information cheaply either way." },
      { kind: "good", backbone: 0, traits: { O: 2, C: 1 },
        text: "\"Take Thursday's retro slot — 15 minutes, pitch it to the team. Strongest objection wins a follow-up.\"",
        fb: "You gave the idea a real arena instead of a private verdict — and signaled to every future hire that better ideas outrank tenure here. Cultural compounding." },
    ],
  },
  {
    id: "return-item", tag: "Everyday", focus: "A",
    text: "The jacket you bought online arrived with a broken zipper. The return window closed… yesterday. Store policy is 'firm.'",
    choices: [
      { kind: "doormat", backbone: -1, traits: { S: -1 },
        text: "\"Ugh, my luck.\" Keep the broken jacket. Wear it zipperless. Tell the story as comedy.",
        fb: "The policy protects them from abuse, not from their own defective zipper. Not even asking is a 100% failure rate you chose voluntarily." },
      { kind: "aggressive", backbone: 0, traits: { A: -2, S: -1 },
        text: "Open the chat with \"Your quality control is a joke and I'll be posting about this everywhere.\"",
        fb: "Opening with threats forces the agent to defend policy instead of helping you. You made the one human with override powers into an opponent." },
      { kind: "assertDirect", backbone: 1, traits: { S: 1, C: 1 },
        text: "\"The zipper arrived broken — that's a defect, not a return. I'd like a replacement or refund. Photos attached. What do you need from me?\"",
        fb: "Reframing return→defect changes which policy applies, and 'what do you need from me' moves it to logistics. Calm, factual, effective." },
      { kind: "assertDiplo", backbone: 1, traits: { A: 1, S: 1 },
        text: "\"I know I'm a day past the window — the zipper was broken on arrival though. I'm hoping you can make an exception; I'd hate for this to be the last order.\"",
        fb: "Acknowledge the rule, give the agent a reason to be a hero, hint at the relationship value. Agents grant exceptions to people who make it easy to say yes." },
    ],
  },
];

/* ---------------- distortion deck ---------------- */
const DISTORTION_TYPES = [
  { id: "catastrophizing", name: "Catastrophizing", short: "Assuming the worst possible outcome is the likely one." },
  { id: "mindreading", name: "Mind reading", short: "Being certain you know what others think — negatively." },
  { id: "fortune", name: "Fortune telling", short: "Predicting failure as if the future were fact." },
  { id: "allornothing", name: "All-or-nothing", short: "One flaw means total failure; no middle exists." },
  { id: "overgeneralization", name: "Overgeneralization", short: "One event becomes 'always' or 'never'." },
  { id: "personalization", name: "Personalization", short: "Taking blame for things you don't control." },
  { id: "shoulds", name: "Should statements", short: "Rigid rules that generate guilt and anger." },
  { id: "emotional", name: "Emotional reasoning", short: "'I feel it, therefore it's true.'" },
  { id: "labeling", name: "Labeling", short: "Turning one behavior into a permanent identity." },
  { id: "filter", name: "Mental filter", short: "Seeing only the negative detail in a full picture." },
  { id: "discounting", name: "Discounting the positive", short: "'That doesn't count' for anything good." },
];

const DISTORTIONS = [
  { thought: "\"My boss said 'we need to talk tomorrow.' I'm getting fired. I should pack my desk tonight.\"",
    answer: "catastrophizing",
    reframe: "\"'We need to talk' has a hundred boring meanings — schedules, projects, feedback. I'll know tomorrow; tonight I know nothing except that I'm guessing the scariest option.\"" },
  { thought: "\"She checked her phone while I was talking. She thinks I'm boring and regrets coming.\"",
    answer: "mindreading",
    reframe: "\"I watched a screen light up and wrote a whole story about my worth. Maybe her sitter texted. If she seems off, I can ask — asking is data, guessing is fiction.\"" },
  { thought: "\"There's no point applying. I won't get the interview anyway.\"",
    answer: "fortune",
    reframe: "\"I've predicted the outcome of a process that hasn't happened. The application costs an hour; the prophecy costs the job with certainty.\"" },
  { thought: "\"I ate one slice of cake, so the whole diet is ruined. Might as well finish the box now.\"",
    answer: "allornothing",
    reframe: "\"One slice is about 300 calories inside a week of good choices — a rounding error, not a verdict. The 'ruined' story is what actually finishes the box.\"" },
  { thought: "\"The date didn't work out. I'll always be alone. Every time, the same thing.\"",
    answer: "overgeneralization",
    reframe: "\"One evening with one incompatible person says nothing about all future evenings with all other people. 'Always' needs more than a sample size of one.\"" },
  { thought: "\"The team lost the client. If I'd just worked this weekend, this wouldn't have happened.\"",
    answer: "personalization",
    reframe: "\"A client relationship involves pricing, timing, their budget, six other people, and luck. I'm assigning myself 100% of a failure I owned maybe 5% of.\"" },
  { thought: "\"I should be able to handle this without help. A stronger person wouldn't need to ask.\"",
    answer: "shoulds",
    reframe: "\"Says who? Asking for help is how competent people stay competent. The 'should' isn't a fact — it's an old rule I never agreed to on purpose.\"" },
  { thought: "\"I feel like a fraud in this role, so I probably am one. Feelings this strong must mean something.\"",
    answer: "emotional",
    reframe: "\"Feelings are real; they're just not evidence. I feel fraudulent AND I passed the same hiring bar as everyone else. Anxiety is loud precisely when it's least informative.\"" },
  { thought: "\"I forgot her birthday. I'm a terrible friend. That's just who I am.\"",
    answer: "labeling",
    reframe: "\"A terrible friend wouldn't feel this bad about it. I'm a good friend who missed a date — the fix is a call and a plan, not a new identity.\"" },
  { thought: "\"The review had nine strengths and one growth area. Clearly they think I'm underperforming.\"",
    answer: "filter",
    reframe: "\"I zoomed 100% of my attention onto 10% of the review. Reread it as written, not as feared: nine strengths is the actual headline.\"" },
  { thought: "\"They only complimented my presentation to be nice. People say those things automatically.\"",
    answer: "discounting",
    reframe: "\"I treat every criticism as gospel and every compliment as charity — that accounting only ever runs one direction. Three people said it unprompted. Let it count.\"" },
  { thought: "\"He didn't laugh at my joke in standup. The whole team probably finds me annoying.\"",
    answer: "mindreading",
    reframe: "\"One person, one joke, 9am. He might not have heard it. I've skipped laughing at funny things a thousand times without it meaning anything.\"" },
  { thought: "\"If I mess up this interview, my career is basically over in this city.\"",
    answer: "catastrophizing",
    reframe: "\"One interview at one company. The industry employs thousands of people who bombed an interview once. Worst realistic case: I practice and book another.\"" },
  { thought: "\"I got a B+ on the project. I'm officially mediocre. Excellence clearly isn't in me.\"",
    answer: "allornothing",
    reframe: "\"B+ sits closer to the top than the middle, and one grade grades one project — not my ceiling. The all-or-nothing scale only has two settings; reality has more.\"" },
  { thought: "\"My friend seemed quiet at lunch. It must be something I did.\"",
    answer: "personalization",
    reframe: "\"People are quiet for a hundred reasons that have nothing to do with me — sleep, work, family, hunger. If I'm the cause, asking will surface it; assuming just convicts me in absentia.\"" },
  { thought: "\"I've been anxious about the flight all week — that has to be a sign something will go wrong.\"",
    answer: "emotional",
    reframe: "\"Anxiety is not a forecast. My dread has zero causal connection to aviation. The feeling is real and worth soothing; as a weather report, it's noise.\"" },
];

/* ---------------- drill deck (Say It With Spine) ---------------- */
const DRILLS = [
  { situation: "A coworker asks you — for the third week running — to cover their Saturday shift.",
    skill: "Saying no without a novel",
    tip: "A no with three excuses invites three counter-offers. A short, warm no is a complete sentence.",
    options: [
      { kind: "doormat", text: "\"Um, I guess so… I sort of had plans but they're probably moveable, it's fine.\"" },
      { kind: "aggressive", text: "\"Wow, again? Do I look like your personal backup plan?\"" },
      { kind: "assert", text: "\"No, I can't this Saturday. Hope you find someone!\"" },
    ] },
  { situation: "Your haircut is visibly not what you asked for. The stylist beams: \"So? Love it?\"",
    skill: "Honest without brutal",
    tip: "The kind lie costs you six weeks of a bad haircut and them a customer. Specific + fixable = kind.",
    options: [
      { kind: "doormat", text: "\"It's great!! So great. Wow.\" (tips 25%, cries in car)" },
      { kind: "assert", text: "\"The sides are shorter than I wanted — can we blend the top to match? Then I think it'll work.\"" },
      { kind: "aggressive", text: "\"Did you listen to anything I said? This is nothing like the photo.\"" },
    ] },
  { situation: "Your landlord promised to fix the heater 'this week' — three weeks ago. Winter has arrived. You're writing the message.",
    skill: "The escalation ladder",
    tip: "Facts, deadline, next step. Escalation isn't rude — it's just the boundary keeping its promises.",
    options: [
      { kind: "doormat", text: "\"Hi! So sorry to bug you again 😅 whenever you get a chance, no rush at all, the heater thing… only if convenient!\"" },
      { kind: "assert", text: "\"Following up: the heater's been out since Nov 2, reported three times. If it's not repaired by Friday, I'll arrange the repair and deduct it per our lease. Happy to coordinate access any day this week.\"" },
      { kind: "aggressive", text: "\"This is ILLEGAL and I've screenshotted EVERYTHING. Expect to hear from my lawyer, my cousin (also a lawyer), and the city.\"" },
    ] },
  { situation: "Mid-meeting, a senior colleague says your team's numbers are 'obviously padded.' Eyes swivel to you.",
    skill: "Fielding a public jab",
    tip: "Calm curiosity beats defensiveness: make the vague accusation get specific — vagueness is where jabs live.",
    options: [
      { kind: "doormat", text: "\"Oh— I mean— sorry, we can redo them, sorry, which parts seemed off…\" (voice trails into the void)" },
      { kind: "assert", text: "\"Strong claim — which figure looks wrong to you? Happy to walk through the source data right now.\"" },
      { kind: "aggressive", text: "\"Padded? That's rich coming from the Q3 forecast guy.\"" },
    ] },
  { situation: "Your mother announces she's booked herself into your guest room for three weeks over the holidays. You can handle one.",
    skill: "Boundaries with family",
    tip: "Decide the limit before the call, say it with love, repeat it without new justifications. Guilt is a feeling, not an instruction.",
    options: [
      { kind: "doormat", text: "\"Three weeks! Great! So great!\" (books own hotel for own house, emotionally)" },
      { kind: "assert", text: "\"I'd love a week together — that's what I can host and still be a person you'd want to visit. Dec 20 to 27, and let's make it a good one?\"" },
      { kind: "aggressive", text: "\"You just booked it? Without asking? This is exactly the problem with you.\"" },
    ] },
  { situation: "The group chat is planning a $900-per-person destination weekend for a birthday. That's your rent.",
    skill: "Money boundaries with friends",
    tip: "Name the limit without the shame spiral. Real friends want you present, not bankrupt — and someone else in that chat is silently relieved you spoke.",
    options: [
      { kind: "doormat", text: "\"Sounds amazing!! 🎉\" (puts it on the card, eats instant noodles till March, resents birthday person)" },
      { kind: "assert", text: "\"That's outside my budget this year — I'm out for the trip, but I'm 100% in for a birthday dinner when you're back. Count me in for that!\"" },
      { kind: "aggressive", text: "\"$900? For a WEEKEND? Some of us have real bills. This group has completely lost touch.\"" },
    ] },
  { situation: "Your dentist's office charged you for a cleaning your insurance already covered. The receptionist sighs: \"Our system says you owe it.\"",
    skill: "The broken record",
    tip: "Same calm sentence, as many times as needed. You don't need new arguments — you need repetition without escalation.",
    options: [
      { kind: "doormat", text: "\"Oh… okay, if the system says so. Can I do a payment plan?\" (pays for the thing that was already paid for)" },
      { kind: "assert", text: "\"The EOB shows it covered in full — here's the copy. I need it removed from my balance. … I understand the system says that; the EOB shows it's covered. I need it removed.\"" },
      { kind: "aggressive", text: "\"Your 'system'? This is FRAUD. I want your manager, the owner, and the number for the state board.\"" },
    ] },
  { situation: "A friend 'jokes' about your accent in front of new people. Third time this month. Everyone chuckles politely.",
    skill: "Naming a pattern",
    tip: "Address patterns privately and specifically. 'Stop doing X' beats 'you always X' — behavior is negotiable, character isn't.",
    options: [
      { kind: "doormat", text: "Laugh along again. Add a self-deprecating bit yourself so it stings on your own terms." },
      { kind: "assert", text: "Later, one-on-one: \"The accent bits in front of new people — drop those. I know it's meant as fun, and it's not fun for me.\"" },
      { kind: "aggressive", text: "In front of everyone: \"At least I speak two languages, unlike some monolingual comedians here.\"" },
    ] },
  { situation: "Your manager assigns you a 'stretch project' that is two people's workloads. You're already at capacity.",
    skill: "Negotiating scope, not worth",
    tip: "Never say 'I can't handle it' — say 'here's what fits.' Make the trade-off their decision, visibly.",
    options: [
      { kind: "doormat", text: "\"Sure, no problem!\" (quietly begins 65-hour weeks; quality slips everywhere; nobody knows why)" },
      { kind: "assert", text: "\"I'm glad you thought of me. To do it well: here's my current list — which of these moves or gets a new owner? I can't do all of it at the quality you expect, and I won't pretend I can.\"" },
      { kind: "aggressive", text: "\"You people have no idea what my workload even is. Does anyone here look at capacity before assigning things?\"" },
    ] },
  { situation: "At a market, the vendor quotes you triple what the local ahead of you just paid. He smiles warmly.",
    skill: "Friendly firmness",
    tip: "Negotiation can be a game both sides enjoy — warm face, firm number, genuine willingness to walk away.",
    options: [
      { kind: "doormat", text: "Pay triple. Avoid eye contact. Speed-walk away clutching your overpriced scarf." },
      { kind: "assert", text: "Grin: \"That's the special visitor price! I heard the real one. I'll do [fair price] — deal?\" Hold the smile. Start to stroll if needed; strolling is negotiating." },
      { kind: "aggressive", text: "\"You think I'm stupid? I SAW what she paid. This is a scam and you know it.\"" },
    ] },
  { situation: "Your date orders for you — without asking — 'trust me, you'll love it.' You had actually decided.",
    skill: "Small corrections early",
    tip: "How you handle small overrides on date three predicts who decides everything by year three. Correct it lightly, watch how they take it — that's the real data.",
    options: [
      { kind: "doormat", text: "Say nothing. Eat the surprise. Wonder, vaguely, if this is a preview." },
      { kind: "assert", text: "Laugh: \"Bold move! I'm actually set on the mushroom risotto — but order that for yourself and I'll trade you bites.\"" },
      { kind: "aggressive", text: "\"Wow. Controlling much? This is a huge red flag, you know.\"" },
    ] },
  { situation: "A colleague keeps 'borrowing' your phone charger without asking and returning it… sometimes.",
    skill: "Low-stakes practice reps",
    tip: "Tiny boundary reps build the muscle for big ones. If you can't reclaim a charger, the salary negotiation has no chance.",
    options: [
      { kind: "doormat", text: "Buy a second charger. Then a third. Consider a charger for the charger-borrower as a preemptive gift." },
      { kind: "assert", text: "\"Hey — ask before taking my charger, and it comes back same day. Deal?\"" },
      { kind: "aggressive", text: "Superglue a note to the charger: 'PROPERTY OF SOMEONE WHOSE STUFF YOU KEEP STEALING.'" },
    ] },
  { situation: "You're 20 minutes into a 'quick call' a vendor said would take five. He's starting slide 14 of 40.",
    skill: "Ending things politely",
    tip: "Your time doesn't need a defense attorney. State the exit, offer the alternative, leave.",
    options: [
      { kind: "doormat", text: "Stay for all 40 slides. Miss your next meeting. Thank HIM at the end." },
      { kind: "assert", text: "\"I need to stop at half past as agreed — send the deck and your two best bullet points, and I'll get you an answer by Friday.\"" },
      { kind: "aggressive", text: "Hang up mid-sentence. If he can't respect five minutes, he doesn't deserve a goodbye." },
    ] },
  { situation: "Your name has been mispronounced by the same colleague for six months. Everyone's copied his version. It grates daily.",
    skill: "It's never too late to correct",
    tip: "The awkwardness of correcting late is one conversation; the alternative is permanent. Light tone, clear correction, done.",
    options: [
      { kind: "doormat", text: "Accept the new name. Consider legally changing it. It's yours now." },
      { kind: "assert", text: "\"By the way — it's ah-NEE-ta, not AN-it-a. I let it slide way too long, so, amnesty for everyone! But that's the one.\"" },
      { kind: "aggressive", text: "\"It's ANITA. A-NEE-TA. Six months, people. SIX MONTHS.\"" },
    ] },
];

/* ---------------- badges ---------------- */
const BADGES = [
  { id: "first-steps", emoji: "👣", name: "First Steps", desc: "Finish your first session of any mode.",
    check: (s) => s.stats.sessionsCompleted >= 1 },
  { id: "spine-5", emoji: "🦴", name: "Growing a Spine", desc: "5 assertive choices.",
    check: (s) => s.stats.assertiveChoices >= 5 },
  { id: "spine-25", emoji: "🦾", name: "Spine of Steel", desc: "25 assertive choices.",
    check: (s) => s.stats.assertiveChoices >= 25 },
  { id: "streak-3", emoji: "🔥", name: "Warm Streak", desc: "Play 3 days in a row.",
    check: (s) => s.streak.best >= 3 },
  { id: "streak-7", emoji: "☄️", name: "On Fire", desc: "Play 7 days in a row.",
    check: (s) => s.streak.best >= 7 },
  { id: "detective", emoji: "🕵️", name: "Distortion Detective", desc: "Correctly name 10 thinking traps.",
    check: (s) => s.stats.distortionsCaught >= 10 },
  { id: "cool-head", emoji: "🧊", name: "Cool Head", desc: "Complete 5 breathing sessions.",
    check: (s) => s.stats.breathSessions >= 5 },
  { id: "no-doormat", emoji: "🚪", name: "Not Your Doormat", desc: "Finish a Situations session with zero doormat picks.",
    check: (s) => s.stats.cleanSessions >= 1 },
  { id: "level-5", emoji: "⭐", name: "Character Growth", desc: "Reach level 5 in any trait.",
    check: (s) => Object.values(s.xp).some((x) => traitLevel(x) >= 5) },
  { id: "well-rounded", emoji: "🎲", name: "Well-Rounded", desc: "Reach level 3 in all five traits.",
    check: (s) => Object.values(s.xp).every((x) => traitLevel(x) >= 3) },
  { id: "citizen", emoji: "🌍", name: "Culture Explorer", desc: "Try 3 different culture profiles.",
    check: (s) => (s.culturesTried || []).length >= 3 },
  { id: "scholar", emoji: "📚", name: "Knows the Rules", desc: "Read the 'How this works' page.",
    check: (s) => !!s.stats.readAbout },
];
