// ============================================================
// POKeMON FRLG: SEVII EDITION - game data
// Types, moves, species, sprites, maps, NPCs
// ============================================================

'use strict';

// ---------- Type chart (Gen 3) ----------
// TYPE_CHART[attacker][defender] = multiplier (missing = 1)
const TYPE_CHART = {
  NORMAL:   { ROCK:.5, GHOST:0, STEEL:.5 },
  FIRE:     { FIRE:.5, WATER:.5, GRASS:2, ICE:2, BUG:2, ROCK:.5, DRAGON:.5, STEEL:2 },
  WATER:    { FIRE:2, WATER:.5, GRASS:.5, GROUND:2, ROCK:2, DRAGON:.5 },
  ELECTRIC: { WATER:2, ELECTRIC:.5, GRASS:.5, GROUND:0, FLYING:2, DRAGON:.5 },
  GRASS:    { FIRE:.5, WATER:2, GRASS:.5, POISON:.5, GROUND:2, FLYING:.5, BUG:.5, ROCK:2, DRAGON:.5, STEEL:.5 },
  ICE:      { FIRE:.5, WATER:.5, GRASS:2, ICE:.5, GROUND:2, FLYING:2, DRAGON:2, STEEL:.5 },
  FIGHTING: { NORMAL:2, ICE:2, POISON:.5, FLYING:.5, PSYCHIC:.5, BUG:.5, ROCK:2, GHOST:0, DARK:2, STEEL:2 },
  POISON:   { GRASS:2, POISON:.5, GROUND:.5, ROCK:.5, GHOST:.5, STEEL:0 },
  GROUND:   { FIRE:2, ELECTRIC:2, GRASS:.5, POISON:2, FLYING:0, BUG:.5, ROCK:2, STEEL:2 },
  FLYING:   { ELECTRIC:.5, GRASS:2, FIGHTING:2, BUG:2, ROCK:.5, STEEL:.5 },
  PSYCHIC:  { FIGHTING:2, POISON:2, PSYCHIC:.5, DARK:0, STEEL:.5 },
  BUG:      { FIRE:.5, GRASS:2, FIGHTING:.5, POISON:.5, FLYING:.5, PSYCHIC:2, GHOST:.5, DARK:2, STEEL:.5 },
  ROCK:     { FIRE:2, ICE:2, FIGHTING:.5, GROUND:.5, FLYING:2, BUG:2, STEEL:.5 },
  GHOST:    { NORMAL:0, PSYCHIC:2, GHOST:2, DARK:.5, STEEL:.5 },
  DRAGON:   { DRAGON:2, STEEL:.5 },
  DARK:     { FIGHTING:.5, PSYCHIC:2, GHOST:2, DARK:.5, STEEL:.5 },
  STEEL:    { FIRE:.5, WATER:.5, ELECTRIC:.5, ICE:2, ROCK:2, STEEL:.5 },
};

// Gen 3: damage category is determined by move TYPE
const SPECIAL_TYPES = ['FIRE','WATER','ELECTRIC','GRASS','ICE','PSYCHIC','DRAGON','DARK'];

// ---------- Moves ----------
// pow 0 = status move. eff: {status, ch} inflict / {stat, stg, who, ch} stage change /
// {heal} percent of max HP / {flinch} chance / prio, neverMiss, selfSleep flags
const MOVES = {
  'SURF':         { type:'WATER',    pow:95,  acc:100, pp:15 },
  'ICE BEAM':     { type:'ICE',      pow:95,  acc:100, pp:10, eff:{status:'FRZ', ch:10} },
  'BITE':         { type:'DARK',     pow:60,  acc:100, pp:25, eff:{flinch:30} },
  'SKULL BASH':   { type:'NORMAL',   pow:100, acc:100, pp:15 },
  'AERIAL ACE':   { type:'FLYING',   pow:60,  acc:0,   pp:20, neverMiss:true },
  'QUICK ATTACK': { type:'NORMAL',   pow:40,  acc:100, pp:30, prio:1 },
  'RETURN':       { type:'NORMAL',   pow:90,  acc:100, pp:20 },
  'SAND-ATTACK':  { type:'GROUND',   pow:0,   acc:100, pp:15, eff:{stat:'acc', stg:-1, who:'foe'} },
  'PSYCHIC':      { type:'PSYCHIC',  pow:90,  acc:100, pp:10, eff:{stat:'spd', stg:-1, who:'foe', ch:10} },
  'SHADOW BALL':  { type:'GHOST',    pow:80,  acc:100, pp:15, eff:{stat:'spd', stg:-1, who:'foe', ch:20} },
  'CALM MIND':    { type:'PSYCHIC',  pow:0,   acc:0,   pp:20, eff:{stat:'spa+spd', stg:1, who:'self'} },
  'RECOVER':      { type:'NORMAL',   pow:0,   acc:0,   pp:10, eff:{heal:50} },
  'BODY SLAM':    { type:'NORMAL',   pow:85,  acc:100, pp:15, eff:{status:'PAR', ch:30} },
  'EARTHQUAKE':   { type:'GROUND',   pow:100, acc:100, pp:10 },
  'REST':         { type:'PSYCHIC',  pow:0,   acc:0,   pp:10, eff:{heal:100}, selfSleep:true },
  'ROCK SLIDE':   { type:'ROCK',     pow:75,  acc:90,  pp:10, eff:{flinch:30} },
  'THUNDERBOLT':  { type:'ELECTRIC', pow:95,  acc:100, pp:15, eff:{status:'PAR', ch:10} },
  'THUNDER WAVE': { type:'ELECTRIC', pow:0,   acc:100, pp:20, eff:{status:'PAR', ch:100} },
  'BRICK BREAK':  { type:'FIGHTING', pow:75,  acc:100, pp:15 },
  'SLUDGE BOMB':  { type:'POISON',   pow:90,  acc:100, pp:10, eff:{status:'PSN', ch:30} },
  'MEGAHORN':     { type:'BUG',      pow:120, acc:85,  pp:10 },
  'DRILL PECK':   { type:'FLYING',   pow:80,  acc:100, pp:20 },
  'FLAME WHEEL':  { type:'FIRE',     pow:60,  acc:100, pp:25, eff:{status:'BRN', ch:10} },
  // wild Pokemon moves
  'PECK':         { type:'FLYING',   pow:35,  acc:100, pp:35 },
  'FURY ATTACK':  { type:'NORMAL',   pow:45,  acc:85,  pp:20 },
  'LEER':         { type:'NORMAL',   pow:0,   acc:100, pp:30, eff:{stat:'def', stg:-1, who:'foe'} },
  'GROWL':        { type:'NORMAL',   pow:0,   acc:100, pp:40, eff:{stat:'atk', stg:-1, who:'foe'} },
  'EMBER':        { type:'FIRE',     pow:40,  acc:100, pp:25, eff:{status:'BRN', ch:10} },
  'STOMP':        { type:'NORMAL',   pow:65,  acc:100, pp:20, eff:{flinch:30} },
  'TAIL WHIP':    { type:'NORMAL',   pow:0,   acc:100, pp:30, eff:{stat:'def', stg:-1, who:'foe'} },
  'TACKLE':       { type:'NORMAL',   pow:35,  acc:95,  pp:35 },
  'ROCK THROW':   { type:'ROCK',     pow:50,  acc:90,  pp:15 },
  'MUD-SLAP':     { type:'GROUND',   pow:20,  acc:100, pp:10, eff:{stat:'acc', stg:-1, who:'foe'} },
  'DEFENSE CURL': { type:'NORMAL',   pow:0,   acc:0,   pp:40, eff:{stat:'def', stg:1, who:'self'} },
  'SCRATCH':      { type:'NORMAL',   pow:40,  acc:100, pp:35 },
  'PAY DAY':      { type:'NORMAL',   pow:40,  acc:100, pp:20 },
  'SCREECH':      { type:'NORMAL',   pow:0,   acc:85,  pp:40, eff:{stat:'def', stg:-2, who:'foe'} },
};

// ---------- Species ----------
// base: [hp, atk, def, spa, spd, spe]
const SPECIES = {
  BLASTOISE: { name:'BLASTOISE', types:['WATER'],             base:[79,83,100,85,105,78],  exp:210, catchRate:45 },
  PIDGEOT:   { name:'PIDGEOT',   types:['NORMAL','FLYING'],   base:[83,80,75,70,70,91],    exp:172, catchRate:45 },
  ALAKAZAM:  { name:'ALAKAZAM',  types:['PSYCHIC'],           base:[55,50,45,135,85,120],  exp:186, catchRate:50 },
  SNORLAX:   { name:'SNORLAX',   types:['NORMAL'],            base:[160,110,65,65,110,30], exp:154, catchRate:25 },
  RAICHU:    { name:'RAICHU',    types:['ELECTRIC'],          base:[60,90,55,90,80,100],   exp:122, catchRate:75 },
  NIDOKING:  { name:'NIDOKING',  types:['POISON','GROUND'],   base:[81,92,77,85,75,85],    exp:195, catchRate:45 },
  SPEAROW:   { name:'SPEAROW',   types:['NORMAL','FLYING'],   base:[40,60,30,31,31,70],    exp:58,  catchRate:255 },
  FEAROW:    { name:'FEAROW',    types:['NORMAL','FLYING'],   base:[65,90,65,61,61,100],   exp:162, catchRate:90 },
  PONYTA:    { name:'PONYTA',    types:['FIRE'],              base:[50,85,55,65,65,90],    exp:152, catchRate:190 },
  RAPIDASH:  { name:'RAPIDASH',  types:['FIRE'],              base:[65,100,70,80,80,105],  exp:192, catchRate:60 },
  GEODUDE:   { name:'GEODUDE',   types:['ROCK','GROUND'],     base:[40,80,100,30,30,20],   exp:73,  catchRate:255 },
  MEOWTH:    { name:'MEOWTH',    types:['NORMAL'],            base:[40,45,35,40,40,90],    exp:69,  catchRate:255 },
};

// ---------- Starting party (post-Elite-Four style FRLG team) ----------
const STARTING_PARTY = [
  { species:'BLASTOISE', level:60, moves:['SURF','ICE BEAM','BITE','SKULL BASH'] },
  { species:'PIDGEOT',   level:57, moves:['AERIAL ACE','QUICK ATTACK','RETURN','SAND-ATTACK'] },
  { species:'ALAKAZAM',  level:54, moves:['PSYCHIC','SHADOW BALL','CALM MIND','RECOVER'] },
  { species:'SNORLAX',   level:56, moves:['BODY SLAM','EARTHQUAKE','REST','ROCK SLIDE'] },
  { species:'RAICHU',    level:53, moves:['THUNDERBOLT','THUNDER WAVE','QUICK ATTACK','BRICK BREAK'] },
  { species:'NIDOKING',  level:55, moves:['EARTHQUAKE','SLUDGE BOMB','MEGAHORN','THUNDERBOLT'] },
];

// ---------- Wild encounters (Kindle Road tall grass, FRLG-style slots) ----------
const WILD_TABLE = [
  { species:'SPEAROW',  weight:25, minLv:30, maxLv:34, moves:['PECK','FURY ATTACK','LEER','GROWL'] },
  { species:'PONYTA',   weight:25, minLv:30, maxLv:34, moves:['EMBER','STOMP','TAIL WHIP','QUICK ATTACK'] },
  { species:'MEOWTH',   weight:20, minLv:29, maxLv:33, moves:['SCRATCH','PAY DAY','BITE','SCREECH'] },
  { species:'GEODUDE',  weight:15, minLv:29, maxLv:33, moves:['ROCK THROW','TACKLE','MUD-SLAP','DEFENSE CURL'] },
  { species:'FEAROW',   weight:8,  minLv:34, maxLv:37, moves:['DRILL PECK','FURY ATTACK','LEER','GROWL'] },
  { species:'RAPIDASH', weight:7,  minLv:34, maxLv:37, moves:['FLAME WHEEL','STOMP','QUICK ATTACK','TAIL WHIP'] },
];

// ---------- Items ----------
const ITEMS = {
  'POTION':       { kind:'heal', amt:20,  desc:'Restores 20 HP.' },
  'SUPER POTION': { kind:'heal', amt:50,  desc:'Restores 50 HP.' },
  'HYPER POTION': { kind:'heal', amt:200, desc:'Restores 200 HP.' },
  'POKe BALL':    { kind:'ball', bonus:1,   desc:'Catches wild POKeMON.' },
  'GREAT BALL':   { kind:'ball', bonus:1.5, desc:'A good, high-performance BALL.' },
  'MASTER BALL':  { kind:'ball', bonus:255, desc:'The best BALL. It never fails.' },
  'RUBY':         { kind:'key',  desc:'A gemstone that glows like embers.' },
  'VS SEEKER':    { kind:'seeker', desc:'Finds TRAINERS keen on a rematch.' },
};

// UI accent color per move type
const TYPE_COLORS = {
  NORMAL:'#a8a068', FIRE:'#e8823c', WATER:'#5a8fd6', ELECTRIC:'#d8b020',
  GRASS:'#58b850', ICE:'#7cc8d8', FIGHTING:'#b0342c', POISON:'#9a4a9a',
  GROUND:'#d0b058', FLYING:'#8a9ae0', PSYCHIC:'#e05888', BUG:'#a8b820',
  ROCK:'#b89e58', GHOST:'#6a5a9a', DRAGON:'#6a48e0', DARK:'#6a5848', STEEL:'#a8a8c0',
};

// area names shown in the sliding location banner, by row range on oneisland
const ZONES = [
  { max: 5,   name: 'EMBER SPA' },
  { max: 29,  name: 'KINDLE ROAD' },
  { max: 43,  name: 'ONE ISLAND' },
  { max: 48,  name: 'TREASURE BEACH' },
  { max: 999, name: 'SEAGALLOP HARBOR' },
];
const MAP_ZONE_NAMES = {
  center: 'POKeMON NETWORK CENTER',
  house: 'ISLANDER\'S HOME',
  summit: 'MT. EMBER SUMMIT',
};

// dialog keyword highlighting (FRLG-style colored proper nouns)
const KEYWORD_COLORS = (() => {
  const place = '#c04838', person = '#2858b8', item = '#1e8a48';
  const map = {};
  const add = (words, c) => words.forEach(w => { map[w] = c; });
  add(['ISLAND!', 'ISLAND', 'ISLANDS', 'SEVII', 'KINDLE', 'ROAD', 'EMBER', 'SPA', 'MT.', 'TREASURE',
    'BEACH', 'SEAGALLOP', 'VERMILION', 'NETWORK', 'CENTER', 'CITY.', 'SUMMIT', 'LEAGUE', 'GYM'], place);
  add(['CELIO', 'CELIO!', 'BILL', 'ATLAS', 'MILO', 'RICK', 'OAK\'s', 'CHAMPION', 'CHAMPION!', 'TRAINER', 'TRAINERS',
    'NURSE', 'HIKER', 'MEOWTH', 'WAILORD', 'MAGIKARP', 'MANKEY', 'SLOWPOKE-tail...',
    'BLASTOISE', 'BLASTOISE?!', 'PIDGEOT', 'PIDGEOT,', 'ALAKAZAM', 'SNORLAX', 'RAICHU', 'NIDOKING',
    'SPEAROW', 'FEAROW', 'PONYTA', 'RAPIDASH', 'GEODUDE', 'POKeMON'], person);
  add(['RUBY', 'RUBY!', 'RUBY,', 'RUBY.', 'BALL', 'BALLS', 'POKe', 'POTION', 'MASTER', 'SEEKER',
    'MACHINE', 'MACHINE!', 'POKeDEX', 'POKeDEX.'], item);
  return map;
})();

const STARTING_BAG = [
  { item:'HYPER POTION', qty:3 },
  { item:'SUPER POTION', qty:5 },
  { item:'POKe BALL',    qty:10 },
  { item:'GREAT BALL',   qty:5 },
  { item:'VS SEEKER',    qty:1 },
];

// ---------- Pixel sprites (24x24, '.'=transparent, k=outline) ----------
const SPRITES = {
  BLASTOISE: {
    pal: { k:'#22262e', b:'#549ad8', B:'#33689f', l:'#8cc4ec', c:'#ecdcb4', C:'#c4a878', s:'#ccd0d8', S:'#8a929e', r:'#7c5c3c', W:'#ffffff' },
    px: [
      '........................',
      '...kk.............kk....',
      '..ksSk...........kSsk...',
      '.kslsSk..kkkkk..ksSlsk..',
      '.kslssk.kbbbbbk.kssssk..',
      '.ksssk.kblbbbbbk.ksssk..',
      '..kSk..kblbbbbbk..kSk...',
      '..kSk..kbkWbkWbk..kSk...',
      '..kSk..kbbbbbbbk..kSk...',
      '.kkbkk..kbkkkbk..kkbkk..',
      'krbbbbkkkbbbbbkkkbbbbrk.',
      'krbbbkbbbbbbbbbbbkbbbrk.',
      'krbbkbbkcccccccckbbkbrk.',
      'krbkbbk.cccccccc.kbbkrk.',
      '.kkbbk.cclccccCc..kbbkk.',
      '.kbbbk.cccccccCc..kbbbk.',
      '.kbbbk.cccccccCc..kbbbk.',
      '..kbk..cccccccCc...kbk..',
      '..kbk..kcCCCCCCk...kbk..',
      '..kk..kbkkkkkkkbk...kk..',
      '.....kbbbk...kbbbk......',
      '....kbbbbk...kbbbbk.....',
      '....kCCCCk...kCCCCk.....',
      '.....kkkk.....kkkk......',
    ],
  },
  PIDGEOT: {
    pal: { k:'#2a241c', t:'#dcb47c', d:'#b08850', r:'#d84830', y:'#ecd44c', w:'#f2e4c4', o:'#e8a030', O:'#b87820', W:'#ffffff' },
    px: [
      '..........kkrk..........',
      '.........kryrk..........',
      '........kryyrk..........',
      '.......kryyrk...........',
      '.......kryyk............',
      '......krykttkk..........',
      '......kyktttttk.........',
      '.......ktkWkttkkoo......',
      '.......kttttttkkOk......',
      '......kttttttttkk.......',
      '.....kttdtttttk.........',
      '....ktdtwwwtttkk........',
      '...ktddwwwwtttttk.......',
      '..ktdddwwwwwttttdk......',
      '..ktddwwwwwwtttttdk.....',
      '.ktdddwwwwwwttttttk.....',
      '.ktddwwwwwwwtttttdk.....',
      '..ktdwwwwwwtttttdk......',
      '...ktwwwwwtttttk........',
      '....kwwwwwttttk.........',
      '...kryyywwtk.kk.........',
      '..kryyykoOk.............',
      '.kryyk.kOk.kO...........',
      '..kkk...kOOk............',
    ],
  },
  ALAKAZAM: {
    pal: { k:'#2a2418', y:'#e0b848', Y:'#b08828', b:'#8a6a40', B:'#5f462a', w:'#f2ead8', s:'#ccd0d8', S:'#8a929e' },
    px: [
      '..ks....ky....yk....sk..',
      '.kssk...kyk..kyk...kssk.',
      '.ksk....kyk..kyk....ksk.',
      '.ksk.....kyyyyk.....ksk.',
      '.kssk...kyyyyyyk...kssk.',
      '..ksk...kykkkkyk...ksk..',
      '..ksk...kyykkyyk...ksk..',
      '..kssk..kyyyyyyk..kssk..',
      '...ksk.kwwkyykwwk.ksk...',
      '...ksk.kwwwyywwwk.ksk...',
      '...kssk.kwkyykwk.kssk...',
      '....ksk..kkyykk..ksk....',
      '....kssk..kyyk..kssk....',
      '.....kskkbbbbbbkksk.....',
      '.....kkbbbbbbbbbbkk.....',
      '.....kybbyybbyybbyk.....',
      '....kyykbyyyyyybkyyk....',
      '....kyk.byyYYyyb.kyk....',
      '....kk..byyYYyyb..kk....',
      '........byykkyyb........',
      '........kyyk.kyyk.......',
      '.......kyyk...kyyk......',
      '......kyyyk...kyyyk.....',
      '......kkkk.....kkkk.....',
    ],
  },
  SNORLAX: {
    pal: { k:'#1c2a2c', n:'#33646c', N:'#234a52', c:'#ecdcbc', C:'#c8ac80', w:'#f2ead8' },
    px: [
      '.......kkkkkkkkk........',
      '.....kknnnnnnnnnkk......',
      '....knnnnnnnnnnnnnk.....',
      '...knnnkknnnnnkknnnk....',
      '...knnnnnnkkknnnnnnk....',
      '...knnnnnkcccknnnnnk....',
      '....knnnkcccccknnnk.....',
      '..kknnnncccccccnnnnkk...',
      '.knnnnncccccccccnnnnnk..',
      'knnnnncccccccccccnnnnnk.',
      'knnnncccccccccccccnnnnk.',
      'knnncccccccccccccccnnnk.',
      'knnncccccccccccccccnnnk.',
      'knnncccccccccccccccnnnk.',
      'knnncccccccccccccccnnnk.',
      'knnncccccccccccccccnnnk.',
      '.knnccccccccccccccnnnk..',
      '.kwknccccccccccccnnkwk..',
      'kwwknnccccccccccnnnkwwk.',
      'kwwwknnnccccccnnnnkwwwk.',
      '.kwknnnnnnnnnnnnnnnkwk..',
      '..kknnnnnnnnnnnnnnkk....',
      '....kkkcwwk.kwwckkk.....',
      '.......kkkk.kkkk........',
    ],
  },
  RAICHU: {
    pal: { k:'#2a2018', o:'#e08c34', O:'#b06820', w:'#f2e0c0', y:'#f0d020', b:'#6a4a20', W:'#ffffff' },
    px: [
      'kbk..................kbk',
      'kobk................kbok',
      '.kobk..............kbok.',
      '..kobkk............kbok.',
      '...kooobk........kbooo..',
      '....kkooobk....kboookk..',
      '......kkoookkkkooookk...',
      '........koooooooook.....',
      '........kokoookoook.....',
      '.......kokWkookWkook....',
      '.......koooooooooook....',
      '......kyokooookookoyk...',
      '......kyyoookkooooyyk...',
      '.......kooooooooook.....',
      '......kooowwwwwooook....',
      '.....koowwwwwwwwwook....',
      '.....koowwwwwwwwwook....',
      '....koowwwwwwwwwwook..k.',
      '....koowwwwwwwwwook..kbk',
      '....kowwwwwwwwwwok..kbk.',
      '....kookwwwwwkookk.kbk..',
      '...kook.kwwk..kookkbk...',
      '..koook..kk....koobk....',
      '..kkkk..........kkk.....',
    ],
  },
  NIDOKING: {
    pal: { k:'#241c2c', p:'#9c6cbc', P:'#6c488c', w:'#dccce8', g:'#b4b8c0', e:'#cbaad8', W:'#ffffff' },
    px: [
      '....kk.....kgk...kk.....',
      '...kppk....kgk..kppk....',
      '..kpeepk...kgk.kpeepk...',
      '..kpeepk..kpppkkpeepk...',
      '..kpeepkkkpppppkpeepk...',
      '...kppkpppppppppkppk....',
      '....kpppkpppppkpppk.....',
      '....kppkWkpppkWkppk.....',
      '....kpppppppppppppk.....',
      '.....kppkkpppkkppk......',
      '....kkpppppppppppkk.....',
      '..kkpppkwwwwwwwkpppkk...',
      '.kpppppkwwwwwwwkpppppk..',
      'kpppppkwwwwwwwwwkpppppk.',
      'kpkpppkwwwwwwwwwkpppkpk.',
      'kpkpppkwwwwwwwwwkpppkpk.',
      '.kkppppkwwwwwwwkppppkk..',
      '..kpppppkwwwwwkppppppk..',
      '...kppppkwwwwwkpppkpppk.',
      '...kpppppkkkkkpppppkPPk.',
      '..kpppppk.....kpppppkk..',
      '..kpppppk.....kpppppk...',
      '..kPPPPPk.....kPPPPPk...',
      '...kkkkk.......kkkkk....',
    ],
  },
  SPEAROW: {
    pal: { k:'#2a2018', b:'#8e5c3a', d:'#6a4028', p:'#e4d4ac', r:'#c05848', o:'#eca89c', O:'#c08070', W:'#ffffff' },
    px: [
      '........................',
      '........kkkk............',
      '......kkbbbbk...........',
      '.....kbbbbbbbk..........',
      '....kbbkWkbbbbk.........',
      '....kbbbbbbbbbk.........',
      '..kkobbbbbbbbbk.........',
      '.koookbbbbbbbk..........',
      '..kkokbbbbbbbk..........',
      '....kbpppbbbbbk.........',
      '....kppppprbbbbk........',
      '...kpppppprrbbbbk.......',
      '...kppppprrrrbbbk.......',
      '...kpppprrrrrrbk........',
      '...kppprrrrrrrk.........',
      '....kpprrrrrrk..........',
      '....kppprrrrk...........',
      '.....kpppprk............',
      '......kpppk.............',
      '......kppk..............',
      '.....koko...............',
      '....kokko...............',
      '...kok..ko..............',
      '........................',
    ],
  },
  FEAROW: {
    pal: { k:'#2a2018', b:'#9e6c42', d:'#7a5030', p:'#e4d4ac', r:'#b04838', o:'#eca89c', O:'#c08070', W:'#ffffff' },
    px: [
      '......krrk..............',
      '.....krrrrk.............',
      '....kkbbbbkk............',
      '...kbbbbbbbbk...........',
      '...kbbkWkbbbbkkkkkkk....',
      '...kbbbbbbbbkoooooook...',
      '....kbbbbbbbkkkkkkkok...',
      '.....kbbbbbbk......ok...',
      '.....kbdbbbbbk..........',
      '......kbdbbbbk..........',
      '....kkpppbbbbbkk........',
      '...kpppppprbbbbbkk......',
      '..kppppppprrbbbbbbk.....',
      '..kpppppprrrrbbbbbbk....',
      '.kppppppprrrrrbbbbk.....',
      '.kppppprrrrrrrrbbk......',
      '.kpppprrrrrrrrrk........',
      '..kppprrrrrrrk..........',
      '...kppprrrrk............',
      '....kppppk..............',
      '.....kppk...............',
      '....koko................',
      '...kok.ko...............',
      '..kok...ko..............',
    ],
  },
  PONYTA: {
    pal: { k:'#2a2418', c:'#ecdcc4', C:'#c4a880', f:'#ec7c2c', F:'#f4c434', h:'#a08860', W:'#ffffff' },
    px: [
      '...........kf...........',
      '..........kfFk.f........',
      '.....kk..kfFfk.kf.......',
      '....kcck.kfFFfkfFk......',
      '...kccckkfFFFfkFfk......',
      '..kckWckcffFFFfFfk......',
      '..kcccckccfFFFFfk.......',
      '..kkccccccckfFfk........',
      '...kccccccck.kfk........',
      '....kccccccck.k.........',
      '.....kcccccck.kf........',
      '.....kccccccckfFk.......',
      '....kcccccccccfFfk......',
      '...kccccccccccckFk......',
      '..kccccccccccccckk......',
      '..kccCcccccccccCk.......',
      '..kcckcccccccckck.......',
      '..kck.kcccccck.kck......',
      '..kck..kcck.....kck.....',
      '.kCk...kcck......kCk....',
      '.khk...khhk......khk....',
      '.khk...khhk......khk....',
      'khhk..khhk......khhk....',
      '.kk....kk........kk.....',
    ],
  },
  RAPIDASH: {
    pal: { k:'#2a2418', c:'#f2ead8', C:'#d0c0a0', f:'#ec7c2c', F:'#f4c434', h:'#b0a080', g:'#e8e0d0', W:'#ffffff' },
    px: [
      '.....kg.....kf..........',
      '.....kgk...kfFk.f.......',
      '....kkgk..kfFfk.kf......',
      '....kcck..kfFFfkfFk.....',
      '...kccckkkfFFFfkFfk.....',
      '..kckWckcffFFFfFfk......',
      '..kcccckccfFFFFfk.......',
      '..kkccccccckfFfk........',
      '...kccccccck.kfkf.......',
      '....kccccccck.kfFk......',
      '.....kcccccck.kFfk......',
      '.....kccccccckfFfk......',
      '....kcccccccccfFfk......',
      '...kccccccccccckFk......',
      '..kccccccccccccckk..f...',
      '..kccCcccccccccCk..kfk..',
      '..kcckcccccccckck.kfFk..',
      '..kck.kcccccck.kckkFfk..',
      '..kck..kcck.....kckfk...',
      '.kCk...kcck......kCkk...',
      '.khk...khhk......khk....',
      '.khk...khhk......khk....',
      'khhk..khhk......khhk....',
      '.kk....kk........kk.....',
    ],
  },
  GEODUDE: {
    pal: { k:'#2a2620', g:'#aa9a88', G:'#7c6c58', d:'#5f5244', W:'#ffffff' },
    px: [
      '........................',
      '........kkkkkkkk........',
      '......kkggggggggkk......',
      '.....kggggggggggggk.....',
      '....kggggggggggggggk....',
      '...kggggggggggggggggk...',
      '..kgggkkgggggggkkgggk...',
      '..kggkWWkgggggkWWkggk...',
      '.kgggkkkkgggggkkkkgggk..',
      'kkggggggggggggggggggkkk.',
      'kggkgggggggggggggggkggk.',
      'kggkggggkkkkkkgggggkggk.',
      'kgggkgggkGGGGkggggkgggk.',
      'kgggkggggkkkkgggggkgggk.',
      '.kgggggggggggggggggggk..',
      '.kGkgggggggggggggggkGk..',
      'kggkkgggggggggggggkkggk.',
      'kgggGkgggggggggggkGgggk.',
      'kggggGkgggggggggkGggggk.',
      '.kggGk.kgggggggk.kGggk..',
      '..kkk...kgggggk...kkk...',
      '.........kGGGk..........',
      '..........kkk...........',
      '........................',
    ],
  },
  MEOWTH: {
    pal: { k:'#2a2418', c:'#ecdcb4', C:'#c4a878', b:'#8a6a40', g:'#ecc434', G:'#c09820', w:'#f8f0e0', p:'#d88888', W:'#ffffff' },
    px: [
      '.........kgk............',
      '........kgGgk...........',
      '..kk.....kgk.....kk.....',
      '.kckk...kkkkk...kkck....',
      '.kcwckkkcccccckkcwck....',
      '.kcwcccccccccccccwck....',
      '..kcccccccccccccck......',
      '..kcccccccccccccck......',
      '.kcckkccccccccckkcck....',
      '.kckWkkccccccckWkkck....',
      '.kcckkccckkkcccckcck....',
      '..kccccckpppkccccck.....',
      '..bkccccckkkcccccb......',
      '...kbccccccccccbk.......',
      '....kkcccccccckk........',
      '.....kccccccccck........',
      '....kccccccccccck.......',
      '...kccckccccckccck..kk..',
      '...kccckccccckccck.kbk..',
      '...kcccccccccccck.kbk...',
      '....kcccccccccckkkbk....',
      '....kcck...kcck.kbk.....',
      '...kccck...kccckbk......',
      '....kkk.....kkk.........',
    ],
  },
};

// Player overworld sprites (16x20), keyed by facing with stand/step frames;
// 'left' is mirrored 'right'
const PLAYER_SPRITES = {
  pal: { k:'#2a2020', r:'#d83c28', R:'#a82818', s:'#ecb488', S:'#c08858', w:'#f4f4f4', W:'#c8c8d0', b:'#3858a0', d:'#283870', h:'#403028' },
  down: [
    [
      '.....kkkkkk.....',
      '....krrrrrrk....',
      '...krrrrrrrrk...',
      '...krRRRRRRrk...',
      '..khksssssskh...',
      '..khsskssksssh..',
      '...ksskssksssk..',
      '...kssssssssk...',
      '....kssSSssk....',
      '...kwkrrrrkwk...',
      '..kwwrrwwrrwwk..',
      '..kswrwwwwrwsk..',
      '..kskwwwwwwksk..',
      '...k.kwwwwk.k...',
      '.....kbbbbk.....',
      '....kbbkkbbk....',
      '....kbbkkbbk....',
      '....kdbkkbdk....',
      '....kkk..kkk....',
      '................',
    ],
    [
      '.....kkkkkk.....',
      '....krrrrrrk....',
      '...krrrrrrrrk...',
      '...krRRRRRRrk...',
      '..khksssssskh...',
      '..khsskssksssh..',
      '...ksskssksssk..',
      '...kssssssssk...',
      '....kssSSssk....',
      '...kwkrrrrkwk...',
      '..kwwrrwwrrwwk..',
      '..kswrwwwwrwsk..',
      '..kskwwwwwwksk..',
      '...k.kwwwwk.k...',
      '.....kbbbbk.....',
      '....kbbkbbbk....',
      '...kdbk.kbbk....',
      '...kkk..kbdk....',
      '.........kkk....',
      '................',
    ],
  ],
  up: [
    [
      '.....kkkkkk.....',
      '....krrrrrrk....',
      '...krrrrrrrrk...',
      '...krrrrrrrrk...',
      '...kRRRRRRRRk...',
      '..khhhhhhhhhhk..',
      '..khhhhhhhhhhk..',
      '...khhhhhhhhk...',
      '....khhhhhhk....',
      '...kwkrrrrkwk...',
      '..kwwrrrrrrwwk..',
      '..kswrrrrrrwsk..',
      '..kskwwwwwwksk..',
      '...k.kwwwwk.k...',
      '.....kbbbbk.....',
      '....kbbkkbbk....',
      '....kbbkkbbk....',
      '....kdbkkbdk....',
      '....kkk..kkk....',
      '................',
    ],
    [
      '.....kkkkkk.....',
      '....krrrrrrk....',
      '...krrrrrrrrk...',
      '...krrrrrrrrk...',
      '...kRRRRRRRRk...',
      '..khhhhhhhhhhk..',
      '..khhhhhhhhhhk..',
      '...khhhhhhhhk...',
      '....khhhhhhk....',
      '...kwkrrrrkwk...',
      '..kwwrrrrrrwwk..',
      '..kswrrrrrrwsk..',
      '..kskwwwwwwksk..',
      '...k.kwwwwk.k...',
      '.....kbbbbk.....',
      '....kbbkbbbk....',
      '...kdbk.kbbk....',
      '...kkk..kbdk....',
      '.........kkk....',
      '................',
    ],
  ],
  right: [
    [
      '.....kkkkkk.....',
      '....krrrrrrk....',
      '...krrrrrrrrk...',
      '...krRRRRRRRk...',
      '...khkssssskh...',
      '...khsssksssh...',
      '....kssskssk....',
      '....kssssssk....',
      '.....kssSsk.....',
      '....kwrrrrkk....',
      '....kwwwwwwsk...',
      '....kwwwwwwsk...',
      '....kwwwwwk.....',
      '.....kwwwk......',
      '.....kbbbbk.....',
      '.....kbkbbk.....',
      '.....kbkbbk.....',
      '.....kdkbdk.....',
      '.....kk.kkk.....',
      '................',
    ],
    [
      '.....kkkkkk.....',
      '....krrrrrrk....',
      '...krrrrrrrrk...',
      '...krRRRRRRRk...',
      '...khkssssskh...',
      '...khsssksssh...',
      '....kssskssk....',
      '....kssssssk....',
      '.....kssSsk.....',
      '....kwrrrrkk....',
      '....kwwwwwwsk...',
      '....kwwwwwwsk...',
      '....kwwwwwk.....',
      '.....kwwwk......',
      '.....kbbbbk.....',
      '....kbbkbbbk....',
      '...kbdk.kbbk....',
      '....kk..kdbk....',
      '.........kk.....',
      '................',
    ],
  ],
};

// ---------- Maps ----------
// Overworld legend:
//  G grass  T tall grass  P path  S sand  W water  F flowers  # mountain rock
//  R tree   ! sign  ~ Ember Spa pool  D pier plank  I item ball
//  A/a/1 PokeCenter roof/wall/door  B/b/2 house roof/wall/door  4 locked door
// Laid out after FRLG One Island: Mt. Ember + Ember Spa north, Kindle Road,
// town with the Network Center, Treasure Beach + Seagallop pier south.
const MAP_ONEISLAND = [
  '##############################',
  '##############################',
  '###########~~~~###############',
  '###########~~~~###############',
  '##########.!PP..##############',
  '##########GGPPGGGG55##########',
  '####RGGGGGGGPPGGGGGGGGGGGR####',
  '####RGTTTGGGPPGGTTTTGGGGGR####',
  '####RGTTTGGGPPGGTTTTGGGGGR####',
  '####RGTTTGGGPPGGTTTTGGGGGR####',
  '####RGGGGGGGPPGGGGGGGFGGGR####',
  '####RGGFGGGGPPGGGGGGGGGGGR####',
  '####RGGGGGGGPPGGGGGGGGGGGR####',
  '####RGTTTTGGPPGGTTTTGGGGGR####',
  '####RGTTTTGGPPGGTTTTGGGGGR####',
  '####RGTTTTGGPPGGTTTTGGGGGR####',
  '####RGGGGGGGPPGGGGGGGGGGGR####',
  '####RGGGGGGGPPGGGGGFGGGGGR####',
  '####RGGFGGGGPPGGGGGGGGGGGR####',
  '####RGGGGGGGPPGGGGGGGGGGGR####',
  '####RGGGGGTTPPGGGTTTGGGGGR####',
  '####RGGGGGTTPPGGGTTTGGGGGR####',
  '####RGGGGGTTPPGGGTTTGGGGGR####',
  '####RGGGGGGGPPGGGGGGGGGGGR####',
  '####RGFGGGGGPPGGGGGGGGGGGR####',
  '####RGGGGGGGPPGGGGGGGFGGGR####',
  '####RGGGGGGGPPGGGGGGGGGGGR####',
  '####RGGGGGGGPPGGGGGGGGGGGR####',
  '####RGGGGGGGPPGGGGGGGGGGGR####',
  '####RGGGGG!GPPGGGGGGGGGGGR####',
  '####RGGGGGGGPPGGGGGGGGGGGR####',
  '####RGGAAAAAPPGGGBBBBBGGGR####',
  '####RGGAAAAAPPGGGBBBBBGGGR####',
  '####RGGaaaaaPPGGGbbbbbGGGR####',
  '####RGGaa1aaPPGGGbb2bbGGGR####',
  '####RGG!PPPPPPGGGGGPGGGGGR####',
  '####RGGGGGGGPPPPPPPPGGGGGR####',
  '####RGGGGGGGPPGGGGGGGGGGGR####',
  '####RGGBBBBBPPGGGGGFGGGGGR####',
  '####RGGBBBBBPPGGGGGGGGGGGR####',
  '####RGGbbbbbPPGGGGGGGGGGGR####',
  '####RGGbb4bbPPGGGGGGGGGGGR####',
  '####RGGGGGGGPPGGGGGGGGGGGR####',
  '####RGGGGGGGPPGGGGGGGGGGGR####',
  '####SSSSSSSSPPSSSSSSSSSSS#####',
  '####S!SSSSSSPPSSSSSSSSSSS#####',
  '####SISSSSSSDDSSSSSISSSSS#####',
  '####SSSSSSSSDDSSSSSSSSSSS#####',
  'WWWWWWSSSSSSDDSSSSSSWWWWWWWWWW',
  'WWWWWWWWWWWWDDWWWWWWWWWWWWWWWW',
  'WWWWWWWWWWWWDDWWWWWWWWWWWWWWWW',
  'WWWWWWWWWWWWDDWWWWWWWWWWWWWWWW',
  'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
  'WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW',
];

// Interior legend: w wall  f floor  c counter  m exit mat  h heal machine
//  p PC/network machine  k bookshelf  t table
const MAP_CENTER = [
  'wwwwwwwww',
  'wkkwhwpkw',
  'wffffffpw',
  'wffcccffw',
  'wfffffffw',
  'wtffffftw',
  'wfffffffw',
  'wwwwmwwww',
];

const MAP_HOUSE = [
  'wwwwwwww',
  'wkkwwtkw',
  'wffffffw',
  'wffffffw',
  'wftffffw',
  'wffffffw',
  'wwwmwwww',
];

// Mt. Ember summit trail: L = lava pool (blocked), 5 = warp back down
const MAP_SUMMIT = [
  '################',
  '################',
  '#####...I..#####',
  '####........####',
  '####.LL..LL.####',
  '#####......#####',
  '######PP########',
  '######PP########',
  '####..PP..######',
  '####..PP..######',
  '####..PP..LL####',
  '####..PP..LL####',
  '####..PPTT..####',
  '####..PPTT..####',
  '####..PP..######',
  '######PP########',
  '######PP########',
  '######PP########',
  '######55########',
  '################',
];

const MAPS = {
  oneisland: {
    grid: MAP_ONEISLAND, outdoor: true, ferry: true,
    volcano: { x: 13, z: -7.5, s: 1 },
    warps: {
      '9,34':  { map:'center', x:4, y:6, dir:'up' },   // PokeCenter door
      '19,34': { map:'house',  x:3, y:5, dir:'up' },   // house door
      // Mt. Ember trail gate, opened by Celio's request
      '18,5':  { map:'summit', x:6, y:17, dir:'up', needQuest:1,
        blockedMsg:['Fallen rocks block the trail up', 'MT. EMBER...'] },
      '19,5':  { map:'summit', x:7, y:17, dir:'up', needQuest:1,
        blockedMsg:['Fallen rocks block the trail up', 'MT. EMBER...'] },
    },
    signs: {
      '11,4':  ['EMBER SPA', 'A hot spring fed by MT. EMBER.', 'Soak to restore your POKeMON.'],
      '10,29': ['TRAINER TIPS', 'A move\'s type matters as much as', 'its power. SURF soaks FIRE types!'],
      '7,35':  ['POKeMON NETWORK CENTER', '"Linking the islands to the world"', '- CELIO'],
      '5,45':  ['TREASURE BEACH', 'Rare treasures wash up here.', 'Finders keepers is the island rule!'],
    },
    npcs: [
      { x:15, y:42, dir:'down', color:'#d06890', name:'ISLAND WOMAN',
        lines:['Welcome to ONE ISLAND!', 'Mainlanders always ask where our', 'GYM is. No GYM here, hon.', 'We settle arguments island-style:', 'whoever spots a WAILORD first', 'wins. Nobody has won since \'92.'],
        lines2:['Back again, hon?', 'Keep an eye on the horizon.', 'I have a good feeling about', 'WAILORD season this year.'] },
      { x:8,  y:47, dir:'down', color:'#6890c0', name:'BEACHCOMBER',
        lines:['Thirty years I\'ve combed this', 'beach for treasure.', 'My greatest find? My dear wife!', 'She drifted in on a kayak.', 'Gahaha! Any POKe BALLS you spot', 'are yours. My back is retired.'],
        lines2:['Find anything good?', 'Once I dug up a gold nugget here.', 'Traded it for a sandwich.', 'Worst deal of my life. Best', 'sandwich, though. Gahaha!'] },
      { x:15, y:27, dir:'down', color:'#68a860', name:'YOUNGSTER',
        lines:['I wear shorts all year. Island', 'life! Breezy AND aerodynamic.', '...Whoa, hold on. A BLASTOISE?!', 'Are you famous or something?', 'Can I get your autograph?!', '...On my shorts?'],
        lines2:['I told everyone at school about', 'you! Nobody believed me.', 'School is on THREE ISLAND, so', 'the story got wet on the way.'] },
      { x:12, y:51, dir:'down', color:'#4878b0', name:'SAILOR',
        lines:['This old girl is the SEAGALLOP.', 'She\'s carried me through three', 'typhoons and one WAILORD sneeze.', 'The sneeze was worse.', 'We\'ll sail again once CELIO\'s', 'machine is humming. No rush, eh?'],
        lines2:['You get your sea legs yet?', 'Takes three voyages, they say.', 'Took me thirty. And one WAILORD.'] },
      { x:12, y:48, dir:'right', color:'#48a898', name:'FISHERMAN',
        lines:['Shh! You\'ll scare the MAGIKARP!', '...', '...Nothing\'s biting anyway.', 'Between you and me, I stopped', 'baiting the hook years ago.', 'It\'s about the peace, friend.'],
        lines2:['...', '......', '.........Bite!', '...No. Just seaweed.', 'Still counts as excitement.'] },
      { x:15, y:5, dir:'down', color:'#a87848', name:'HIKER',
        lines:['I\'ve hiked MT. EMBER thirty times!', 'My knees? Gravel. Pure gravel.', 'But one soak in EMBER SPA and I', 'bounce around like a MANKEY!', 'Your POKeMON will love it too.', 'Just don\'t drink the water.'],
        lines2:['A trainer once asked me WHY not', 'to drink the spa water.', 'Friend, a GEODUDE bathes in it.', 'That\'s why.'] },
      { x:16, y:12, dir:'left', color:'#c8a038', name:'BIRD KEEPER MILO',
        trainer: {
          id: 'birdkeeper',
          intro: ['My birds train against the gales', 'that howl off MT. EMBER!', 'A stranger with a PIDGEOT, eh?', 'This island\'s sky only has room', 'for one flock!'],
          party: [
            { species:'SPEAROW', level:31, moves:['PECK','FURY ATTACK','LEER','GROWL'] },
            { species:'FEAROW',  level:34, moves:['DRILL PECK','FURY ATTACK','LEER','GROWL'] },
          ],
          prize: 1360,
          defeat: 'My flock! Plucked and plated!',
          win: ['Your PIDGEOT barely flapped.', 'Unbelievable.', 'Fine - the sky has room for two', 'flocks. But ONLY two!'],
          after: ['My SPEAROW has been sulking.', 'I told him, losing to a CHAMPION', 'is basically a badge of honor.'],
        } },
      { x:9, y:22, dir:'right', color:'#5a9858', name:'CAMPER RICK',
        trainer: {
          id: 'camper',
          intro: ['Three weeks I\'ve camped on', 'KINDLE ROAD! No tent, no bedroll.', 'Just me, my POKeMON, and the', 'volcano\'s warmth.', '...Mostly because a MEOWTH stole', 'my tent. ANYWAY! Battle time!'],
          party: [
            { species:'GEODUDE', level:31, moves:['ROCK THROW','TACKLE','MUD-SLAP','DEFENSE CURL'] },
            { species:'PONYTA',  level:34, moves:['EMBER','STOMP','TAIL WHIP','QUICK ATTACK'] },
          ],
          prize: 1360,
          defeat: 'Even my GEODUDE got rolled!',
          win: ['Not. Even. Close.', 'So THAT\'s a LEAGUE CHAMPION...', 'Say, you didn\'t happen to pass a', 'MEOWTH dragging a tent, did you?'],
          after: ['Still no tent. The MEOWTH added', 'a little flag to it. Taunting me.', 'One day I\'ll beat a CHAMPION...', 'right after I beat that MEOWTH.'],
        } },
    ],
  },
  summit: {
    grid: MAP_SUMMIT, outdoor: true, rocky: true, warm: true,
    volcano: { x: 8, z: -16, s: 1.3 },
    wildTable: [
      { species:'GEODUDE', weight:40, minLv:38, maxLv:42, moves:['ROCK THROW','TACKLE','MUD-SLAP','DEFENSE CURL'] },
      { species:'PONYTA',  weight:35, minLv:38, maxLv:42, moves:['FLAME WHEEL','STOMP','TAIL WHIP','QUICK ATTACK'] },
      { species:'FEAROW',  weight:25, minLv:40, maxLv:44, moves:['DRILL PECK','FURY ATTACK','LEER','GROWL'] },
    ],
    warps: {
      '6,18': { map:'oneisland', x:18, y:6, dir:'down' },
      '7,18': { map:'oneisland', x:19, y:6, dir:'down' },
    },
    signs: {
      '8,3': ['MT. EMBER SUMMIT', 'The earth here breathes fire.', 'Watch your step.'],
    },
    npcs: [
      { x:6, y:9, dir:'right', color:'#c05848', name:'COOLTRAINER ATLAS',
        trainer: {
          id: 'atlas',
          intro: ['So you\'re the CHAMPION the whole', 'island is whispering about.', 'I train up here where the ground', 'itself burns. My team was forged', 'in this volcano\'s breath!', 'Show me what forged YOURS!'],
          party: [
            { species:'FEAROW',   level:46, moves:['DRILL PECK','FURY ATTACK','LEER','GROWL'] },
            { species:'RAPIDASH', level:47, moves:['FLAME WHEEL','STOMP','QUICK ATTACK','TAIL WHIP'] },
            { species:'SNORLAX',  level:49, moves:['BODY SLAM','EARTHQUAKE','REST','ROCK SLIDE'] },
          ],
          prize: 4900,
          defeat: 'Scorched... utterly scorched!',
          win: ['So that\'s a champion\'s fire...', 'It burns hotter than any volcano.', 'The RUBY rests on the plateau', 'above. It\'s yours - you\'ve more', 'than earned the right.'],
          after: ['With the RUBY, CELIO\'s machine', 'might actually work.', 'Tell him ATLAS says hello.', 'We used to be lab partners!'],
        } },
    ],
  },
  center: {
    grid: MAP_CENTER, outdoor: false,
    warps: { '4,7': { map:'oneisland', x:9, y:35, dir:'down' } },
    signs: {},
    npcs: [
      { x:4, y:2, dir:'down', color:'#e88898', name:'NURSE', action:'heal',
        lines:['Welcome to the POKeMON CENTER!', 'Shall I restore your POKeMON', 'to full health?'] },
      { x:7, y:3, dir:'left', color:'#c05848', name:'CELIO', action:'celio' },
    ],
  },
  house: {
    grid: MAP_HOUSE, outdoor: false,
    warps: { '3,6': { map:'oneisland', x:19, y:35, dir:'down' } },
    signs: {},
    npcs: [
      { x:5, y:2, dir:'down', color:'#a878c0', name:'OLD WOMAN', action:'gift',
        lines:['Oh my! A trainer, in my kitchen!', 'You have my grandson\'s eyes.', 'And his muddy shoes. Ohoho!', 'He never writes, you know. Too', 'busy "training" on TWO ISLAND.', 'Here, take these. And eat more!'] },
    ],
  },
};

const GIFT_ITEMS = [
  { item:'HYPER POTION', qty:2 },
  { item:'GREAT BALL', qty:3 },
];

// Item balls lying on the ground ('I' tiles), keyed by map then 'x,y'
const ITEM_BALLS = {
  oneisland: {
    '5,46':  { item:'GREAT BALL',   qty:3 },
    '19,46': { item:'HYPER POTION', qty:2 },
  },
  summit: {
    '8,2': { item:'RUBY', qty:1 },
  },
};

// Celio's quest dialog, keyed by quest stage
const CELIO_DIALOG = {
  0: ['Oh! You must be the trainer BILL', 'wrote about. I\'m CELIO!',
      'My NETWORK MACHINE could link the', 'SEVII ISLANDS to the whole world -',
      'but it needs a gem to focus its', 'signal. A RUBY, to be exact.',
      'One rests at MT. EMBER\'s summit.', 'I\'ve asked the HIKER to clear the',
      'trail north of EMBER SPA for you.', 'Would you fetch it? Please?'],
  1: ['The trail past EMBER SPA is open!', 'The RUBY should be at the summit.',
      'Mind the lava. And the trainer up', 'there... he\'s the intense type.'],
  2: ['Is that... the RUBY?!', 'It\'s PERFECT! Hand it here -',
      'careful - gently - YES!'],
  3: ['Listen to it HUM! The machine', 'works! BILL is going to flip!',
      'The SEAGALLOP can sail again, and', 'it\'s all thanks to you.',
      'You\'re welcome on ONE ISLAND', 'forever, CHAMPION.'],
};
